### ISSUE TITLE
Dead Link on Website

### ISSUE THREAD

**Issue by jbteves** [afni/afni#106]
Not sure if this is the right place to post, but there is a dead link on the AFNI website [here](https://afni.nimh.nih.gov/sscc/gangc), linked to from [here](https://afni.nimh.nih.gov/node/13).

**Comment by mrneont** [comment]
Howdy-

Thanks for noting that.  Gang hasn't actually been fired from the group (that I know of), but instead some of his old notes/information has migrated to here:
https://afni.nimh.nih.gov/gangchen_homepage
and here:
https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/STATISTICS/main_toc.html

We will update those links appropriately-- thanks!

--pt

**Comment by mrneont** [comment]
... and Brian P has now fixed the link on the webpage, actually going to this as the correct location for Gang's notes at present:
https://sscc.nimh.nih.gov/sscc/gangc/

Cheers,
pt
