### ISSUE TITLE
Orientation matrix changes when using volreg block in afni_proc.py

### ISSUE THREAD

**Issue by benoitberanger** [afni/afni#107]
Hello,

For multi-echo processing, I use the convenient `afni_proc.py` to prepare & execute processing steps. In this case : `tshift`, `volreg`.
After converting back to _Nifti_ files at the end using `3dAFNItoNIFTI`, I noticed the orientation matrix changed. And I don't see why.

Here is the **afni_proc.py** code :

```
 cd /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04; 
 afni_proc.py -subj_id 2019_05_20_NEUROTOPLEX_Sujet04 \
 -out_dir /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/afni \
 -scr_overwrite \
 -dsets_me_run /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/S12_Run_Visuel_1/e*.nii \
 -dsets_me_run /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/S12_Run_Visuel_1/e*.nii \
 -blocks tshift volreg \
 -tshift_interp -heptic \
 -tshift_opts_ts -TR 1.3 -tpattern @/mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/sliceonsets.txt \
 -reg_echo 1                  \
 -volreg_align_to first       \
 -volreg_interp -quintic      \
 -volreg_zpad 4               \
 -execute \
 
 3dAFNItoNIFTI -verb -verb -prefix /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/S12_Run_Visuel_1/vte1.nii /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/afni/pb02.2019_05_20_NEUROTOPLEX_Sujet04.r01.e01.volreg+orig 
 3dAFNItoNIFTI -verb -verb -prefix /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/S12_Run_Visuel_1/vte2.nii /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/afni/pb02.2019_05_20_NEUROTOPLEX_Sujet04.r01.e02.volreg+orig 
 3dAFNItoNIFTI -verb -verb -prefix /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/S12_Run_Visuel_1/vte3.nii /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/afni/pb02.2019_05_20_NEUROTOPLEX_Sujet04.r01.e03.volreg+orig 
 3dAFNItoNIFTI -verb -verb -prefix /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/S12_Run_Visuel_1/vte1.nii /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/afni/pb02.2019_05_20_NEUROTOPLEX_Sujet04.r02.e01.volreg+orig 
 3dAFNItoNIFTI -verb -verb -prefix /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/S12_Run_Visuel_1/vte2.nii /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/afni/pb02.2019_05_20_NEUROTOPLEX_Sujet04.r02.e02.volreg+orig 
 3dAFNItoNIFTI -verb -verb -prefix /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/S12_Run_Visuel_1/vte3.nii /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/afni/pb02.2019_05_20_NEUROTOPLEX_Sujet04.r02.e03.volreg+orig 
```

Here is the **orientation matrix**:
```

benoit.beranger@icm-cenir-le33: /mnt/data/benoit/project/job_meica_afni/neurotoplex/nifti/2019_05_20_NEUROTOPLEX_Sujet04/S12_Run_Visuel_1 $ mrinfo e1.nii vte1.nii 
************************************************
Image:               "e1.nii"
************************************************
  Dimensions:        74 x 74 x 48 x 696
  Voxel size:        3 x 3 x 3 x 1300
  Data strides:      [ -1 2 3 4 ]
  Format:            NIfTI-1.1
  Data type:         unsigned 16 bit integer (little endian)
  Intensity scaling: offset = 0, multiplier = 1
  Transform:                    1           0           0        -108
                               -0      0.9751     -0.2215      -80.29
                               -0      0.2215      0.9751       -77.1
************************************************
Image:               "vte1.nii"
************************************************
  Dimensions:        74 x 74 x 48 x 696
  Voxel size:        3 x 3 x 3 x 1.3
  Data strides:      [ -1 2 3 4 ]
  Format:            NIfTI-1.1
  Data type:         32 bit float (little endian)
  Intensity scaling: offset = 0, multiplier = 1
  Transform:                    1          -0          -0        -108
                                0           1          -0      -80.29
                               -0           0           1       -77.1

```

Before I was using `-volreg_align_to MIN_OUTLIER` and in some rare cases, the the brain as *cropped* because of shifted down.
Now I changed to `first` and it seem to be more stable, no brain cropped.
But still, I would like to know why the orientation changes.

Best,
Benoît

**Comment by afni-rickr** [comment]
Hi @benoitberanger,
This is something we have been pondering a bit lately, but it is messy.
Here 3dvolreg is creating a time series of alignment transformations, which are then applied to each echo by 3dAllineate.  It is 3dAllineate that drops the obliquity information (which truncates that matrix to the nearest cardinal grid).  In order for 3dAllineate to decide to keep the obliquity information, it would need to know that the input, output and any master (none, here) grids match, including obliquity, as well as the more complicated fact that the applied transformation comes between 2 datasets that also have the same obliquity, which comes from a different command.
Anyway, we will continue pondering this.  For now, you can copy the obliquity information to the resulting datasets (either vte?.nii or pb02*.HEAD), e.g.
`3drefit -atrcopy pb01.2019_05_20_NEUROTOPLEX_Sujet04.r01.e01.tshift+orig IJK_TO_DICOM_REAL vte1.nii`

Also, 'first' will not be more stable than 'MIN_OUTLIER'.  Any cropping depends on how the subject moves.  MIN_OUTLIER is preferable because one can be pretty sure the subject was not moving then.  Aligning to a volume that has motion in it (or doesn't match the time series in any other way) would likely add a sort of motion noise to the registration result.
- rick

**Comment by benoitberanger** [comment]
Hi @afni-rickr,

Thanks for your answer !
Ok I see, this effect is due to the implementation and choices done in `3dAllineate`.
In fact, It's not a problem to have different orientation compared to the input file, but I was curious.
After mutli-echo denoising ([TEDANA](https://github.com/ME-ICA/tedana)), the coregistration to the T1 will do the job.
But it's good to know that `3drefit` have the option to change the orientation if needed.

Best,
Benoît
