### ISSUE TITLE
Documentation Discrepancy in unWarpEPI.py

### ISSUE THREAD

**Issue by jbteves** [afni/afni#109]
In /abin/unWarpEPI.py, the help text notes that the script can be used to undistort EPI images using a B0 map:
>Routine to unwarp EPI data set using another data set with opposite polarity or B0 field map  

However, the source doesn't contain any facilities for doing so and there are no command line arguments to do so. Is there a function to undistort B0's related to unWarpEPI.py? And if not, could the documentation be rewritten to reflect that it must be a reverse phase encode?

Thanks so much!

**Comment by afni-rickr** [comment]
Hi @jbteves, I don't think B0 correction made it into unWarpEPI.py, but there is a related discussion on the message board: [distortion correction using field maps in AFNI](https://afni.nimh.nih.gov/afni/community/board/read.php?1,161616).

**Comment by jbteves** [comment]
Thanks for the note @afni-rickr; that's my office-mate doing their own investigation, interestingly. Are there plans to make this integration into `unWarpEPI.py` in the near future?

**Comment by afni-rickr** [comment]
Hi @jbteves, there is now a epi_b0_correct.py program available, by @mrneont.  I'll take the B0 mention out of unWarpEPI.py.  Thanks.

**Comment by jbteves** [comment]
Thanks @afni-rickr !
