### ISSUE TITLE
3dAFNItoNIFTI in afni_proc.py ?

### ISSUE THREAD

**Issue by benoitberanger** [afni/afni#111]
Hello,

Is it planned to incorporate an option in `afni_proc.py` to convert the **HEAD/BRIK** files to **NIFTI** after the last processing step ?

Best,
Benoît

**Comment by afni-rickr** [comment]
This gets brought up once in a while, but no, that will probably not happen.  There are many datasets output by afni_proc.py (so it would be hard to decide which ones to convert), and the most important ones (e.g. stats), cannot even be properly stored in NIFTI.  And in such a case, one would probably want to copy it out of the results directory anyway, so the conversion to NIFTI can be done with that command.

**Comment by benoitberanger** [comment]
I see, it's more complicated than I expected, probably because I use `afni_proc.py` for a simple case (multi-echo pre-processing).
Thanks for your answer.

Best,
Benoît
