### ISSUE TITLE
afni_proc.py using volreg when the field of view changed

### ISSUE THREAD

**Issue by benoitberanger** [afni/afni#112]
Hello,

During a scan, the subject had to get out of the magnet between 2 fMRI scans of the same task.
So the orientation differs a bit between the two runs.

Here is the orientation matrix, and a screenshot of the volume :

```
************************************************
Image:               "S12_Run_Visuel_1/e2.nii"
************************************************
  Dimensions:        74 x 74 x 48 x 698
  Voxel size:        3 x 3 x 3 x 1300
  Data strides:      [ -1 2 3 4 ]
  Format:            NIfTI-1.1
  Data type:         unsigned 16 bit integer (little endian)
  Intensity scaling: offset = 0, multiplier = 1
  Transform:                    1           0           0        -108
                               -0      0.9641     -0.2656      -64.58
                               -0      0.2656      0.9641      -68.89
************************************************
Image:               "S20_Run_Visuel_2/e2.nii"
************************************************
  Dimensions:        74 x 74 x 48 x 699
  Voxel size:        3 x 3 x 3 x 1300
  Data strides:      [ -1 2 3 4 ]
  Format:            NIfTI-1.1
  Data type:         unsigned 16 bit integer (little endian)
  Intensity scaling: offset = 0, multiplier = 1
  Transform:                    1           0           0        -108
                               -0      0.9641     -0.2656      -73.83
                               -0      0.2656      0.9641      -90.48
```
![run1_run2_raw](https://user-images.githubusercontent.com/16976839/60263276-84d29400-98e0-11e9-9fea-cf1b55551242.gif)

After run `afni_proc.py` with the same workflow as https://github.com/afni/afni/issues/107#issue-458767824, the new orientation matrix and screenshot of the volume are : 

```
************************************************
Image:               "S12_Run_Visuel_1/vte2.nii"
************************************************
  Dimensions:        74 x 74 x 48 x 698
  Voxel size:        3 x 3 x 3 x 1.3
  Data strides:      [ -1 2 3 4 ]
  Format:            NIfTI-1.1
  Data type:         32 bit float (little endian)
  Intensity scaling: offset = 0, multiplier = 1
  Transform:                    1          -0          -0        -108
                                0           1          -0      -64.58
                               -0           0           1      -68.89
************************************************
Image:               "S20_Run_Visuel_2/vte2.nii"
************************************************
  Dimensions:        74 x 74 x 48 x 699
  Voxel size:        3 x 3 x 3 x 1.3
  Data strides:      [ -1 2 3 4 ]
  Format:            NIfTI-1.1
  Data type:         32 bit float (little endian)
  Intensity scaling: offset = 0, multiplier = 1
  Transform:                    1          -0          -0        -108
                                0           1          -0      -73.83
                               -0           0           1      -90.48
```
![run1_run2_after_tshift_volreg](https://user-images.githubusercontent.com/16976839/60263522-26f27c00-98e1-11e9-821c-2917cdf91d6d.gif)

I know *volreg* block using `3dvolreg` & `3dAllineate` did job as expected.
However, there must be a trick to avoid this brain cropped.
Maybe `3drefit` have some options ?
Or something else ?

What would be recommended ?

Best,
Benoît

**Comment by benoitberanger** [comment]
I tried `-volreg_align_e2a`, and it worked almost fine, the "seperated" runs were aligned the anatomy, no cropping of the field-of-view.

However, instead of a center mass + rigid body transformation, it seems this step adds a reslice. The final EPI volumes seem more "blurry", and their grid has the same orientation as the anatomy (like sagital strict).
Is there a way to disable the reslice of the grid ? I tried `-align_opts_aea -ginormous_move -cost lpc+ZZ -resample off` but didn't seem to change anything. (ginormous_move for the align_center).

**Comment by afni-rickr** [comment]
Added blurriness is expected here, though maybe it would be nicer using wsinc5 resampling via "-volreg_warp_final_interp wsinc5".
Particularly since that aligns the EPI to the anat, expect the EPI to move, regardless of which grid it is on.  That means the new data points will not be on top of the old ones, and as each voxel is a combination of its 8 neighbors from the original grid, a blur is incurred.  Try wsinc5 and see if you like it more.

**Comment by benoitberanger** [comment]
Since I didn't find a solution for runs with different positions in the magnet, I tried another strategy.

Now I perform `afni_proc.py` on each run separately. So, there is no **run->run** realignment problem, no need of **run->anat** realignment.

**Comment by afni-rickr** [comment]
@benoitberanger I think there is another option that I have not mentioned, one that uses 3dAllineate for cross-run volreg.  Consider using "-volreg_post_vr_allin yes" as in this example:
```
                 -volreg_align_to MIN_OUTLIER                               \
                 -volreg_post_vr_allin yes                                  \
                 -volreg_pvra_base_index MIN_OUTLIER                        \
                 -volreg_warp_final_interp wsinc5                           \
```
That will have each run aligned to its own MIN_OUTLIER base via 3dvolreg using 6-parmeter rigid body transformations.  Then all of those base volumes are aligned to the global MIN_OUTLIER volume across all runs via 3dAllineate using 12-parameter affines.  Give that a try to see if it improves this issue.  Thanks.

**Comment by benoitberanger** [comment]
@afni-rickr I already tried the cross-run volreg.
It did not work, the result is the the about the as in the pics in the top of the issue : some volumes are still cropped.

**Comment by mrneont** [comment]
Hi-

What if you ran something like:
`@Align_Centers -cm -base RUN_000 -dset RUN_001 -prefix RUN_001_al`
to pre-align the centers of mass of the EPIs before putting them into afni_proc.py?  That should get RUN_000 and RUN_001_al very close to centered before runnign afni_proc.py.

--pt

**Comment by mrneont** [comment]
Closing due to 4 months inactivity after a solution was proposed.
