### ISSUE TITLE
dead URL in 3dLME docstring

### ISSUE THREAD

**Issue by yarikoptic** [afni/afni#114]
found one https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dLME.html
present in the codebase:
```shell
$> git grep -n https://afni.nimh.nih.gov/sscc/gangc/LME.html 
src/R_scripts/3dLME.R:71: https://afni.nimh.nih.gov/sscc/gangc/LME.html
```
that URL leads to

Page not found
The requested page "/sscc/gangc/LME.html" could not be found.

**Comment by afni-rickr** [comment]
I will pester GC, thanks!

**Comment by mrneont** [comment]
This link has been fixed now in the code;  will be present in the next build.
