### ISSUE TITLE
question: optimal "workflow" for hierarchical(?) model

### ISSUE THREAD

**Issue by yarikoptic** [afni/afni#115]
we have following levels
- 5 studies (different PIs, different or the same scanners/scanning params, similar designs)
- ~100 subjects per study
- up to 2 sessions
- 2-3 runs (depending on a study, sensored away some runs/subjects so 2 runs are guaranteed to have)

variables of interest
- basic task contrasts (motor, n-back memory)
- we will initially start with no additional variables just to check if all is good with a QA condition (motor) but then expand with demographics (per subject/session such as age) and clinical assessments (per session)

notes:
- within some studies might be different magnets (and their software versions) used for portion of subject/sessions.  Not sure if worth adding as a group/level, but worth at least trying to absorb some variance into additional variables of non (or may be of) interest
- we would start with the a single session, and only 3 studies of the same age group but then would like to use both sessions in studies were available and account/analyze different age groups

What would be the best tool and approach to model this large scale study using AFNI to pull everything together? ;-)

**Comment by afni-gangc** [comment]
Yes, such a hierarchical data structure can be handled in AFNI. Which specific program to use in AFNI would depend on the details of your data structure and variables. For example, are all the studies, sessions and runs  going to be pooled together? Does age vary across sessions? Are some subjects genetically related?

**Comment by yarikoptic** [comment]
> For example, are all the studies, sessions and runs going to be pooled together?
> Does age vary across sessions? Are some subjects genetically related?
eventually all studies will be pulled together, and 2 out of 5 are youth when the other 3 - adults. There are ages in adults studies which come close to the upper age within youth (IIRC 18 yo).
For the moment we are pooling 3 adult studies.  Age will also be added as a regressor. There is no known genetic information/relation between subjects.

**Comment by afni-gangc** [comment]
How many contrasts are involved? Any within-subject (or repeated-measures) factors other than contrast?

I assume that each of subject's age does not change during each study. Modeling age can be tricky if linearity assumption is severely violated, but it might be OK if the age range in your case is not so wide.

**Comment by yarikoptic** [comment]
> How many contrasts are involved? Any within-subject (or repeated-measures) factors other than the contrasts?

I think we will have a single contrast to come from each subject session (`2back - 0back`). Subject age can change between sessions.  For starters we will analyze only session 1 and see how/what we would do with multiple sessions later on.  I do not think that ages would be too distant between sessions so we might not even try to account for intersession distance in age.

**Comment by afni-gangc** [comment]
For a single session with one contrast, you don't have any within-subject variables. In that case, 3dMVM would be the way to go for whole-brain voxelwise analysis. 

If you're willing to define a list of regions (e.g., 20, 100, or 1000) using information from the literature or various versions of parcellations, you could perform region-based analysis using the program 'RBA' to avoid the issue of multiple comparisons.

**Comment by mrneont** [comment]
This seems to have been answered satisfactorily, since there haven't been any follow-up questions for well over a year.
