### ISSUE TITLE
FYI: https://afni.nimh.nih.gov/pub/dist/data/misc/ is not reachable ATM

### ISSUE THREAD

**Issue by yarikoptic** [afni/afni#121]
although it is for 2018 bootcamp, I saw a link on https://codeconvergence.org/ to the prior test dataset.  Thought to prepare datalad dataset with all needed materials (for the past year to start with).  but apparently it is NA

```shell
$> wget https://afni.nimh.nih.gov/pub/dist/data/misc/UCLA_pamenc20.tgz
--2019-10-10 11:38:07--  https://afni.nimh.nih.gov/pub/dist/data/misc/UCLA_pamenc20.tgz
Resolving afni.nimh.nih.gov (afni.nimh.nih.gov)... 156.40.187.114, 2607:f220:419:4103::114
Connecting to afni.nimh.nih.gov (afni.nimh.nih.gov)|156.40.187.114|:443... failed: Connection timed out.
Connecting to afni.nimh.nih.gov (afni.nimh.nih.gov)|2607:f220:419:4103::114|:443... failed: Network is unreachable.
1 35347 ->4.....................................:Thu 10 Oct 2019 11:38:23 AM EDT:.
hopa:/tmp
$> sudo tcptraceroute afni.nimh.nih.gov 80                                  
[sudo] password for yoh: 
Running:
	traceroute -T -O info -p 80 afni.nimh.nih.gov 
traceroute to afni.nimh.nih.gov (156.40.187.114), 30 hops max, 60 byte packets
 1  _gateway (10.31.176.1)  2.411 ms  2.541 ms  3.003 ms
 2  berry1-crt.border1-rt.dartmouth.edu (129.170.1.42)  1.769 ms  2.626 ms  4.030 ms
 3  i2-cleveland.border1-rt.dartmouth.edu (129.170.9.241)  5.231 ms  5.567 ms  5.987 ms
 4  et-7-0-0.4079.rtsw.bost.net.internet2.edu (162.252.70.97)  10.707 ms  10.735 ms  10.734 ms
 5  et-7-0-0.4079.rtsw.hart2.net.internet2.edu (162.252.70.99)  13.909 ms  13.919 ms  13.915 ms
 6  ae-2.4079.rtsw.newy32aoa.net.internet2.edu (162.252.70.101)  17.212 ms  15.466 ms  13.843 ms
 7  ae-3.4079.rtsw.wash.net.internet2.edu (162.252.70.138)  19.019 ms  19.033 ms  19.001 ms
 8  ae-0.4079.rtsw2.ashb.net.internet2.edu (162.252.70.137)  19.128 ms  19.140 ms  19.167 ms
 9  ae-2.4079.rtsw.ashb.net.internet2.edu (162.252.70.74)  19.161 ms  18.741 ms  18.556 ms
10  et-11-3-0-1275.clpk-core.maxgigapop.net (206.196.177.2)  19.263 ms  19.545 ms  19.815 ms
11  nih-re.demarc.maxgigapop.net (206.196.177.183)  20.745 ms  20.754 ms  20.723 ms
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

```

**Comment by afni-rickr** [comment]
Hey there @yarikoptic.  Yeah, afni has been a bit grumpy since last night.  Stay tuned...

**Comment by afni-rickr** [comment]
It.  Is.   Aliiiiiiiiiive... aaaaaaaughh!

**Comment by yarikoptic** [comment]
awesome!  So do you think that for this code convergence you end up using some of the older materials or everything would be brand new?  I would love to create datalad dataset to facilitate easier access etc ;)

**Comment by leej3** [comment]
How about https://github.com/afni/afni_ci_test_data.git

**Comment by yarikoptic** [comment]
Woohoo! 
- [x] test dataset

What about containers? ;-) datalad containers-add could add even docker layers, and containers-run "instantiate" the image/container locally on the fly. BUT unfortunately no URLs for them yet to fetch from docker hub. 
Singularity containers - somewhat similar about URLs since now they are short-lived. But as for running singularity on non Linux - checkout https://github.com/ReproNim/containers/blob/master/scripts/singularity_cmd ;-)

**Comment by leej3** [comment]
Circleci generates containers with and without coverage enabled (~ 5 and 19GB respectively). The tests are currently failing because I have to do some fixing of the test data (adding some missing files). Once I fix that we will have a container people can use. 
 
I haven't found the dev container especially useful because the make build tool struggles to do an out of tree build and so it's difficult to mount one's codebase into the container. I'm still tapping away at getting the make build up and running: 
https://github.com/afni/afni/pull/119

That would be a much smaller container, and one could mount the codebase in and resume a pre-existing build in another directory. Depending on what people are working on, one should suit their needs.

singularity_cmd is very neat.

**Comment by afni-rickr** [comment]
We believe this is okay to close.
