### ISSUE TITLE
Unbundling imcat

### ISSUE THREAD

**Issue by TheChymera** [afni/afni#128]
I just nocticed that afni ships its own version of [imcat](https://github.com/stolk/imcat). On Gentoo we have a package for that software. So I will just make AFNI depend on that. However, I would also like to stop AFNI from trying to get/install that file itself. How can I best do this?

**Comment by leej3** [comment]
Thanks @TheChymera. @yarikoptic and I are currently working our way through optionally using system installations of various bits of software. We shall add this to the list.

**Comment by leej3** [comment]
@mrneont has informed me this isn't the same imcat. We could consider renaming ours if this is going to cause many people problems. Otherwise altering where AFNI appears in your path or aliasing imcat would be a couple of hacky solutions...

**Comment by mrneont** [comment]
Howdy- And my first vote would probably be for a path-based fix, rather than renaming a program.  

If you don't use AFNI's imcat, then having the AFNI binaries later in your path would solve it;  otherwise, aliasing one of the imcats could work?

**Comment by yarikoptic** [comment]
@TheChymera are you sure it is the same `imcat`? AFNI's https://github.com/afni/afni/blob/master/src/imcat.c has nothing to do with "Preview any size image in a terminal window."

**Comment by TheChymera** [comment]
@yarikoptic oh my, you are right... The other imcat is a smaller project (well, it's general purpose so has a bigger target audience, but fewer forks and followers on GH), but imcat is the name of the entire project, so if you guys would be wiling to, it would be really cool if you can be so nice rename the executable.

I could submit a patch just sed-ing all your code. Unless you would rather do it yourselves.

@leej3 creating AFNIs own path is something I would really like to avoid. FSL does it this way and it's a total catastrophe, commonly leading to confusion and portability issues in packages which depend on it.

**Comment by yarikoptic** [comment]
Fwiw in NeuroDebian we ship only afni  in /usr/bin, the rest for under /usr/lib/afni/bin and users need to source /etc/afni/afni.sh to get PATH adjusted. Renaming tools in afni if unlikely to happen since could break user scripts.

**Comment by TheChymera** [comment]
@yarikoptic 
> and users need to source /etc/afni/afni.sh to get PATH adjusted

Well, that's a bit of an issue in and of itself, but it still won't address the namespace problem if both executables have the same name, right? 

@leej3 
> We could consider renaming ours if this is going to cause many people problems.

Let me know if you would want to do this. I think it is the best solution, and I'd be willing to help out.

@mrneont 
>  otherwise, aliasing one of the imcats could work?

After a brief look at the source code, it seems `imcat` is not dynamically linked to by other afni functions. Is that true? If so aliasing would be really easy (though it might still cause confusion if it's done independently of you).
