### ISSUE TITLE
Concatenate affine transforms

### ISSUE THREAD

**Issue by oesteban** [afni/afni#129]
Following up on #116, now that I'm capable of replicating deoblique matrices AFNI calculates, my next step would be composing them with another transform (even identity).

Is there any AFNI tool to compose WARPDRIVE_MATVEC_FOR_000000 and WARPDRIVE_MATVEC_INV_000000 with some other affine in the middle?
Ideally, I could have a 3dallineate file with 3 rows and the tool would give me 1 row. Whatever other solution is also fine.

Finally I would check the following:

1. Apply the original transform with the original oblique datasets.
2. Deoblique the datasets (moving/reference, input/base) and then apply the transform coming from combining the (de)oblique matrices as described above.

Both should give the same result (or very close) if nearest is used in interpolation.

**Comment by mrneont** [comment]
Hi, Oscar-

cat_matvec can concatenate affine warps (and invert any of them).

Perhaps we can also discuss this in person.
