### ISSUE TITLE
Is the AFNI webite

### ISSUE THREAD

**Issue by KevinAquino** [afni/afni#15]

**Comment by KevinAquino** [comment]
Sorry I couldn't find any other place to pose this question.

Also is there a makefile for OS X 10.10?

**Comment by afni-rickr** [comment]
Thanks for the bump.  It would be better to post questions on the AFNI Message Board: http://afni.nimh.nih.gov/afni/community/board .
We do not yet compile on any 10.10 system, but it is not clear why one would expect any difference from previous versions.  If you are running into errors, please feel free to post them.
