### ISSUE TITLE
Python3.8 bug

### ISSUE THREAD

**Issue by neurolabusc** [afni/afni#162]
Hello
  This is a feature request for [Python 3 support for AFNI](https://afni.nimh.nih.gov/afni/community/board/read.php?1,155380,158660#msg-158660). Python 2 is now [retired](https://pythonclock.org/), and I just installed AFNI on the daily snapshot of Ubuntu 20.04, which removes Python2 by default, and comes with Python 3.8 as its primary version of Python. The AFNI script `lib_system_check.py` fails as it uses the [platform.dist() function](https://docs.python.org/3.6/library/platform.html#platform.dist) deprecated in Python3.5 and removed in 3.8:

```
File "/home/chris/abin/afnipy/lib_system_check.py", line 79, in show_general_sys_info
    if checkdist: dstr = tostr(platform.dist())
AttributeError: module 'platform' has no attribute 'dist'

```
The current bug is this code:

```
   try:    dstr = tostr(platform.linux_distribution())
   except: checkdist = 1
```
With minimal fix is:
```
      if   self.system == 'Linux':
         try:    dstr = tostr(platform.linux_distribution())
         except: 
            checkdist = 1
            try: platform.dist()
            except: checkdist = 0
```
The comprehensive solution is:

```
      if   self.system == 'Linux':
         try:    dstr = tostr(platform.linux_distribution())
         except: 
            checkdist = 1
            try: platform.dist()
            except:
               checkdist = 0
               try:
                  import distro
                  dstr = tostr(distro.linux_distribution(full_distribution_name=False))
                  dstr =  ''.join(dstr)
               except:
                  pass
```

Which for my system (where the `distro` package is included by default) will print
```
distribution:         ubuntu 20.04 focal
```

**Comment by leej3** [comment]
looks good. Thanks for the fix.
