### ISSUE TITLE
Python Qt4

### ISSUE THREAD

**Issue by neurolabusc** [afni/afni#163]
The upcoming Ubuntu 20.04 [removes Qt4 support](https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-20.04-LTS-No-Qt4). The script `afni_system_check.py -check_all` reports:
```
** failed to load module PyQt4
-- PyQt4 is no longer needed for an AFNI bootcamp
```
As a feature request:
 1. Update [Ubuntu install web page](https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu18.html) to note that the package `python-qt4` is optional. 
 2. Are any features lost by NOT having qt4. If it is not required at all, why check for it. If it may cause issues with some features, perhaps `afni_system_check.py` can warn users which functions are impacted.

**Comment by mrneont** [comment]
Hi, again, Chris-

Thanks for these suggestions.  We have sorted out the build instricutison for Ubuntu 20.04,
https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu20.html
and addressed these issues (no more PyQt4 in the instructions, indeed).

Re. PyQt4:  we do have some GUIs for building processing commands-- uber_subject.py, for example-- that use PyQt4.  Over time, we have recommended people not use these, though, and just jump to building afni_proc.py commands from one of the many examples in the help file, from the website, and/or from publications where people report their afni_proc.py command (e.g., in supplements or appendices).  So, at the moment, we will let the uber_subject.py functionality lapse, but that shouldn't really affect users.
