### ISSUE TITLE
Installing AFNI on Ubuntu 20.04

### ISSUE THREAD

**Issue by neurolabusc** [afni/afni#166]
The upcoming Ubuntu 20.04 (and [19.10](https://github.com/oracle/fastr/issues/121)) do not provide the package libgfortran3. The R installer [suggests](https://www.graalvm.org/docs/reference-manual/languages/r/) the following package
```
sudo apt install libgfortran-8-dev libgomp1
```
As a feature request, it would be nice to have AFNI instructions for the upcoming 20.04 LTS. This is a tiny change from the current instructions for installing AFNI on [Ubuntu 18.04](https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu18.html).

**Comment by mrneont** [comment]
Hi, Chris-

Thanks for this suggestion.  At the moment, we have no computers with Ubuntu 20.04 installed on them, but we definitely will look to have new instructions as the new LTS release rolls out.  My understanding was that the official release will be April 23, 2020:
https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule

We are very happy to have any suggestions from your beta testing of the new OS!

**Comment by mrneont** [comment]
Hi, Chris-

We have finally gotten around to sorting things out with the Ubuntu 20.04 build.  Thanks a lot for your comments here on this;  they made things pretty straightforward for us in the end (indeed, we incorporated the Aptitude line you provide here).

Here are the new AFNI installation instructions for Ubuntu 20.04 (note there is a "quick" version at the bottom of the page):
https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu20.html
I have to check the non-LTS things at some point, but I imagine that this would apply to the 19.*, as well.
