### ISSUE TITLE
GCC10 -fcommon switch prevents AFNI 19.3.12 from building

### ISSUE THREAD

**Issue by TheChymera** [afni/afni#179]
No idea if this is still a thing for the latest release, but `=afni-19.3.12`, the latest release I ship for Gentoo Linux, fails to build with the following [build.log](https://github.com/afni/afni/files/4704936/71ed40.log).

The issue goes away if I build it with `CFLAGS=-fcommon`.

The source might be patchable just by making `zzpltr_` and `zzzplt_` extern in `pwritf.c` and `pwritf.h`, but I'm not that familiar with the code. If you could confirm this, it would really help me continue to support this version for GCC-10 as well.

**Comment by afni-rickr** [comment]
Hi @TheChymera.  Yes, -fcommon seems to be the default on most systems, but perhaps not on yours (since -fno-common does not appear in that build.log).  Have you tried applying extern in pwritf.c and verifying that the rest of the package builds?  Well, I will test that here...

**Comment by afni-rickr** [comment]
Okay, it seems like that was just an oversight, those externs have been added.  And for the record, the rest did build with -fno-common.  Thanks for bringing it up.

**Comment by TheChymera** [comment]
@afni-rickr thank you :)
