### ISSUE TITLE
compilation issue `Kfatal error: ^[[m^[[KPython.h: No such file or directory`

### ISSUE THREAD

**Issue by TheChymera** [afni/afni#213]
The compilation instructions distributed by Gentoo Linux for `=afni-20.1.16` have recently stopped working, and we get the following [build.log](https://github.com/afni/afni/files/5354112/build.log).

The summary of the failure afaict, is:

```
x86_64-pc-linux-gnu-gcc -march=native -O3 -pipe -fPIC -DREAD_WRITE_64 -DLINUX2 -Wcomment -Wformat -DUSE_TRACING -DHAVE_XDBE  -DDONT_USE_XTDESTROY -c thd_selenium.c -O1 -DSELENIUM_READY -I/usr/include/python2.7 -I. -I/usr/include -Inifti/nifti2 -Inifti/niftilib -Inifti/nifticdf -Inifti/znzlib -I3DEdge/src -Irickr -Ileej3 -DHAVE_ZLIB -DHAVE_GIFTI -If2c
^[[01m^[[Kthd_selenium.c:18:10:^[[m^[[K ^[[01;31m^[[Kfatal error: ^[[m^[[KPython.h: No such file or directory
   18 | #include ^[[01;31m^[[K<Python.h>^[[m^[[K
      |          ^[[01;31m^[[K^~~~~~~~~~^[[m^[[K
compilation terminated.
make: *** [Makefile.INCLUDE:3272: thd_selenium.o] Error 1
```

Is this perhaps indicative of some dependency we may have missed and only always “incidentally” provided beforehand, or perhaps something else, like incompatibility with newer dep versions?

**Comment by leej3** [comment]
The problem is this:
https://github.com/afni/afni/blob/12a430057e0c434934b76a1bd082dd15af4eac40/src/thd_selenium.c#L18

It was likely incidentally included and now that python2 is EOL it has started to not be present on systems.

You could not define SELENIUM_READY if you didn't need the web browser driving capability. It's typically defined in the driving make files:
https://github.com/afni/afni/blob/12a430057e0c434934b76a1bd082dd15af4eac40/src/Makefile.linux_fedora_28_shared#L26

@afni-dglen do you still use this? I didn't define this for the cmake build, perhaps I should?

**Comment by TheChymera** [comment]
@leej3 by “not define” you mean I could delete the respective line? Perhaps the next line should then also be removed?

https://github.com/afni/afni/blob/12a430057e0c434934b76a1bd082dd15af4eac40/src/Makefile.linux_fedora_28_shared#L26-L27

**Comment by leej3** [comment]
> By “not define” you mean I could delete the respective line?

Yes, or at rather the corresponding line in the makefile you happen to be using. 

> Perhaps the next line should then also be removed?

That would certainly be tidier yes.

I don't have a sense of how much people use this functionality though. It is possible that updating the lines to use the python3 development header (and corresponding linker flag) would be better.

**Comment by leej3** [comment]
I checked with @afni-dglen. It was for some specific atlas functionality in the afni GUI. He doesn't know of anyone who uses it so it's safe to remove for your users.

**Comment by TheChymera** [comment]
ok, turns out the makefile I needed to edit was a different one. The build is now fixed in Gentoo https://gitweb.gentoo.org/proj/sci.git/commit/?id=83fd8b496d322f3f6130ff251f0567486f35a14a .

Thank you :)

**Comment by leej3** [comment]
Happy to hear it! Thanks for letting us know.
