### ISSUE TITLE
NIFTI_INTENT_NONE is valid

### ISSUE THREAD

**Issue by crossmanith** [afni/afni#225]
gifti_intent_from_string() should not return NIFTI_INTENT_NONE in case of failure because NIFTI_INTENT_NONE is a valid intent code.

**Comment by crossmanith** [comment]
I'm trying to fix this. First I've cloned the afni repository and built it without any modifications. Next I've edited afni/src/gifti/gifti_io.c and built again. While debugging my test program I see that a copy of gifticlib is created in afni_build/_deps/gifti_clib-src. So my modifications in the source tree aren't used. 

How can I force the build process to use the modifications in the source tree and not the original code copied to the build tree?

**Comment by leej3** [comment]
Thanks for the contribution.

You can override the fetch contents behavior of cmake by setting  `FETCH_CONTENT_SOURCE_DIR_<DEPNAME>` to your version, where `<DEPNAME>` is the dependency name in uppercase. The dependency names can be found in the [cmake file managing dependencies](https://github.com/afni/afni/blob/8f96943c5c471fd2beddd4d80d1b721d8a92b8aa/cmake/afni_project_dependencies.cmake#L165). So assuming gifti_clib and afni are in your home directory the following should be sufficient for you to complete you debugging:
 
```
cmake -DFETCH_CONTENT_SOURCE_DIR_GIFTI_CLIB=~/gifti_clib ~/afni
```

**Comment by leej3** [comment]
Apologies, there was a typo there. It's `FETCHCONTENT_SOURCE_DIR_<DEPNAME>` (no underscore in the first part of the variable)

**Comment by crossmanith** [comment]
I've created a PR for gifti_clib instead.

**Comment by leej3** [comment]
Sounds good.
