### ISSUE TITLE
3dmaskave bug: compiler dependent behavior for MRI_byte images

### ISSUE THREAD

**Issue by neurolabusc** [afni/afni#235]
The validation test_3dmaskave.py warns [`3dmaskave removes all voxels on MacOS for some reason`](https://github.com/afni/afni/blob/158ab9f1943b9649d61ca85b0217f92cd0d752de/tests/scripts/test_3dmaskave.py).

There is a bug on [line 523 of 3dmaskave.c](https://github.com/afni/afni/blob/dab76581b2ddef36dd4d5974f122e9759732c5c5/src/3dmaskave.c#L523)

The code
```
case MRI_byte:{
          ...
            mtop = (byte) MRI_TYPE_maxval[MRI_short] ;
```
should read
```
case MRI_byte:{
          ...
            mtop = (byte) MRI_TYPE_maxval[MRI_byte] ;
```
Rationale: MRI_TYPE_maxval[MRI_short] is a float equal to 32767.0 while MRI_TYPE_maxval[MRI_byte] is a float equal to 255.0. Typecasting to (byte) will result in a value 0..255, with different compilers presumably dealing with overflow differently (in my testing, gcc set this to 255, and clang set it to 0).

**Comment by neurolabusc** [comment]
Same bug is in [plug_maskave.c](https://github.com/afni/afni/blob/dab76581b2ddef36dd4d5974f122e9759732c5c5/src/plug_maskave.c#L254)

**Comment by neurolabusc** [comment]
Same bug is in [thd_makemask.c](https://github.com/afni/afni/blob/dab76581b2ddef36dd4d5974f122e9759732c5c5/src/thd_makemask.c#L94)

**Comment by neurolabusc** [comment]
I suggest [mri_to_byte.c](https://github.com/afni/afni/blob/dab76581b2ddef36dd4d5974f122e9759732c5c5/src/mri_to_byte.c#L233) is changed from:
```
mbot = (byte) -MRI_TYPE_maxval[MRI_byte];
```
to read
```
mbot = 0;
```
Rationale: Since MRI_TYPE_maxval[MRI_byte] is a float equal to 255.0, this code typecasts -255.0 to an unsigned integer. [Casting a negative float value to an unsigned integral type is not a defined behavior](https://www.ibm.com/support/pages/assigning-negative-float-value-unsigned-integral-type-yields-undefined-value-stored-type).

**Comment by leej3** [comment]
thanks for debugging this. I think this was causing issues for #218 too.

**Comment by mrneont** [comment]
@neurolabusc -- Thanks for pointing this out.  These are all fixed as suggested now.

**Comment by mrneont** [comment]
These have all been dealt with.

Thanks.
