### ISSUE TITLE
3dDWUncert macOS compile

### ISSUE THREAD

**Issue by neurolabusc** [afni/afni#242]
3dDWUncert does not compile on MacOS with the default Clang/LLVM compiler because it does not set the required [OpenMP flags](https://mac.r-project.org/openmp/).
  3dDWUncert will not compile on MacOS due to this [line 238 of /Makefile.ptaylor.INCLUDE](https://github.com/afni/afni/blob/3761661c301db92e1a2b495e4979ddce05468793/src/ptaylor/Makefile.ptaylor.INCLUDE#L238)

1. My simple solution was to change
`  $(CCOMP_PT) -fopenmp -o 3dDWUncert 3dDWUncert.o  ${AFNI_3dOBJS} \`
to read
`  $(CCOMP_PT) $(OMPFLAG) -o 3dDWUncert 3dDWUncert.o  ${AFNI_3dOBJS} \`

This requires the makefile which calls this file to set the variable "OMPFLAG" appropriately, which it should to compile the rest of AFNI (e.g. this pull request for using [Clang on MacOS](https://github.com/afni/afni/pull/233))

2. A more complicated solution would be to adapt your makefile to be self contained. Here you could set this flag locally in your script rather than rely on the global variable. The only wrinkle to this approach is that Apple aliases "gcc" and "g++" to call Clang/LLVM, and I am not sure what happens if the modified script is run on a Mac where the user compiles with the true gcc instead of Clang. It is possible that true gcc ignores these flags, or it may cause the compilation to fail.  

```
MY_OMPFLAG = -fopenmp
ifneq ($(OS),Windows_NT)
	OS = $(shell uname)
 	ifeq "$(OS)" "Darwin"
		MY_OMPFLAG = -Xpreprocessor -fopenmp -lomp		
	endif
endif
...
  $(CCOMP_PT) $(MY_OMPFLAG) -o 3dDWUncert 3dDWUncert.o  ${AFNI_3dOBJS} \
```

**Comment by mrneont** [comment]
... and this (-> simple change, #1) has now been implemented by DRG and merged into the AFNI code base.  Grazie.
