### ISSUE TITLE
3dAFNItoNIFTI always prints AFNI version, even when redirecting output

### ISSUE THREAD

**Issue by jbteves** [afni/afni#244]
Even when redirecting output, 3dAFNItoNIFTI seems to always print its version. This is not consistent with behavior in other AFNI programs. Sample output:
```
(tdev) [tevesjb@cn0895 heunis_rtme]$ 3dAFNItoNIML > help.txt
(afni_dev) tevesjb@MH02217074MACLT src % 3dAFNItoNIFTI > help.txt
++ 3dAFNItoNIFTI: AFNI version=AFNI_20.3.01 (Oct 19 2020) [64-bit]
```
When checking the file, I saw that `PRINT_VERSION` is placed *before* `machdep()` is called, whereas in 3dAFNItoNIML it is *after* `machdep()` is called. I'm not sure if this could cause such an effect, but I have a branch I can open a PR with if Team AFNI thinks that might be related. Unfortunately I seem to be struggling with making the appropriate binary for testing (both make and cmake indicate missing dependencies), so I'm not sure if it would work anyway.

**Comment by pmolfese** [comment]
It's actually the "PRINT_VERSION("3dAFNItoNIFTI") coming before the "machdep".
