### ISSUE TITLE
RetroTS.py throws "Unexpected EOF while parsing" from PeakFinder.py

### ISSUE THREAD

**Issue by ahartleupmc** [afni/afni#249]
When trying to run RetroTS.py I am consistently getting an error at the line "v.append(float(line.strip()))" (308) from PeakFinder.py. This appears to have something to do with converting that value to a float, as when I try to break that line into its component parts it is the float() line that continues to throw the error.

**Comment by pmolfese** [comment]
Can you attach some source files so we can take a look at it?

**Comment by ahartleupmc** [comment]
Thanks for the quick response. Attached are our original cardiac and respiratory files ("wpc..."), as well as updated files in which I removed any text that was not numbers as that seemed to create issues. The .txt file extensions were added only so that I could upload them to github, as intially they had only .puls and .resp extensions.

The EOF error occurs in AFNI version 20.2.15 installed using the Ubuntu precompiled binary on Ubuntu 18.04. I tried running RetroTS on another machine with AFNI 18.2.15 installed with the Ubuntu precompiled binary on Ubuntu 18.04 and got a similar issue before removing the non-numerical text in the data files. After making that change I got a new error (see attached screenshot). Thanks so much for your help.
![turing_RetroTS_error](https://user-images.githubusercontent.com/67325215/106663968-72b3df80-6572-11eb-9d79-e16e90d2cb92.PNG)


[wpc7888_50003_20190724.resp.txt](https://github.com/afni/afni/files/5914504/wpc7888_50003_20190724.resp.txt)
[respiratory.resp.txt](https://github.com/afni/afni/files/5914505/respiratory.resp.txt)


[pulse.puls.txt](https://github.com/afni/afni/files/5914502/pulse.puls.txt)
[wpc7888_50003_20190724.puls.txt](https://github.com/afni/afni/files/5914503/wpc7888_50003_20190724.puls.txt)

**Comment by pmolfese** [comment]
Thanks! There's some header info on the resp and pulse files that looks inconsistent with the rest of the data.  Also it looks like your files are different lengths.  How were the files collected?  Biopac?  Is the sampling rate the same for both? 

`> dim(resp)
[1] 2314975
> dim(pulse)
[1] 2329610`

**Comment by ahartleupmc** [comment]
Thanks for looking at them. I'll need to get in touch with one of our physicists to obtain that information. I'll get back to you ASAP.

**Comment by ahartleupmc** [comment]
So I heard back and got a few answers. The files were collected with Biopac. The sampling rate for resp is 50 hz and pulse is 400 hz. According to our physicist it's expected that the files are of different lengths. I hope this is helpful, thanks.

**Comment by pmolfese** [comment]
You'll need to downsample the ECG or (better yet) upsample the respiratory file to match.  You can use 3dUpsample in AFNI to do this.  
https://afni.nimh.nih.gov/afni/community/board/read.php?1,150027,153064#msg-153064
https://afni.nimh.nih.gov/afni/community/board/read.php?1,159710,159761#msg-159761

Once you do that the process should work  better. The output of RetroTS should match the number of TRs you have in your MRI recordings.  You can use options in afni_proc.py to trim the first (or last) samples from the file if necessary.  

I'm not sure it's worth adding this feature directly to RetroTS at this time - but we could certainly think about it.  Let me know if this solves your issue so I can close it out.
