### ISSUE TITLE
Variance Groups in AFNI

### ISSUE THREAD

**Issue by TheChymera** [afni/afni#251]
Is there any analogue of the “variance group” specification from FSL (as described here: https://brainder.org/2017/02/24/group-indicator-fsl/ ) in AFNI?

**Comment by afni-gangc** [comment]
If "variance group" means heteroscedasticty (different variance is assumed across groups), there are two approaches to handling it in AFNI: (1) use option -unpooled in 3dttest++; (2) specify the variance-covariance structure through linear mixed-effects modeling with 3dLMEr.

**Comment by TheChymera** [comment]
@afni-gangc yes, that is what I meant.

> (2) specify the variance-covariance structure through linear mixed-effects modeling with 3dLMEr
The help text doesn't seem to mention this use case,
I assume this would be done by specifying the variance structure in the R formula, and adding a new column for the variance groups? Do you perhaps know where I could find an example of this?

**Comment by afni-gangc** [comment]
@TheChymera Actually it is 3dLME, not 3dLMEr, that has the functionality of handling heteroscedasticty. However, I would have to add an option in the current scripting interface through the "weights/varStruct" structure of the R package nlme.
