### ISSUE TITLE
Tag older code versions

### ISSUE THREAD

**Issue by dmwelch** [afni/afni#258]
I'm trying to build AFNI 2011_12_21_1014 (~dab76581b2ddef36dd4d5974f122e9759732c5c5~ 728df1c0c3e5dc64a4feee7f7f8c7e7d90975138) using [neurodocker](https://github.com/ReproNim/neurodocker) (so I can run regression testing for a legacy server that has been decommissioned) but I have to manually insert the git commit to the Dockerfile because Neurodocker only supports the latest version.  One of the challenges that prevents them supporting older versions is that they are not tagged reliably in Git.  Please tag legacy versions so external tools can recreate these environments with confidence.

Estimated time for task: 1-3 hours (depending on records)

**Comment by dmwelch** [comment]
There are three use cases that I can see that would need these older tags:

1) legacy systems requiring regression testing after moving from a very old version of AFNI fails and you need to know what's the newest version that still gives similar results/in the same format/etc. but updating to the latest version is not an option e.g. a tool depends on AFNI, but doesn't support later version, 
1) when you need to recreate a system in containers after the hardware has been decommissioned (again, where updating AFNI is not desirable), and 
1) to reproduce results from research papers based on early versions of AFNI.  

As I couldn't get the binary available at https://afni.nimh.nih.gov/pub/dist/tgz/AFNI_ARCHIVE/ to work in a Docker container, I needed to build from source and hence had to interrogate the repository for what I could only guess was the commit the binary was based on.  

I don't forsee this happening frequently with respect to later installs, but I would argue it is important enough to the scientific community that uses AFNI to have all binary snapshots from the past correspond to a specific commit in the VCS, especially with regards to making earlier research reproducible.

**Comment by mrneont** [comment]
Hi @dmwelch -

Thanks for putting some specific examples out there to make this more concrete.

Something that applies to all those cases:  we don't officially deprecate code, but it is hard to see how code from before 2015 could be maintained anymore.  (And we actually do try to keep AFNI pretty low on dependency requirements and able to run on some pretty old machines---even some of our build machines are super old;  we tried keeping a Mac OS 10.7 build around weeeelllll past its sell-by date, but eventually it just got to be too much of a headache.)  It also seems like this general retro-tagging would be more than just a couple hours of work.

Additionally, I am not sure what it would mean to validate a very old study of very old software on a very old computer (assuming those exact scripts from the original study even exist---people weren't in the habit of saving+propagating them in those dark ages), when no one today would use that code version in a study.  And if the program had *not* changed, then validating it on a very old system does not seem to add any information for researchers in the field, either.  Any of these validations could be done with code available back to late-2015.  It is hard to see how tests on lots of samples of code further back than this would be broadly useful in the present day.  

If you have a couple specific commits of interest from dates prior to the existing tags (starting in late-2015), then we could try to help with this.  But broadly retro-tagging the very old code does not seem feasible.

**Comment by dmwelch** [comment]
@mrneont you're suggesting that your userbase comb through your history to find the versions AFNI should have been recorded by the lab already?  With all due respect, whether it's a few hours or a few days, this is the responsibility of the AUTHORS of the code, not the users.  

Is it an undesirable task? Yes.  
Do your users have the ability to even identify those commits purely from the VCS history? _Maybe._ 
Can they do it as reliably? **No. The AFNI lab has (or should have!) the records to reconcile commits to releases.  Anything else is guesswork.**

**Comment by mrneont** [comment]
@dmwelch 

I am a bit confused.  We have tags (447 of them) for every AFNI release going back to late-2015:
https://github.com/afni/afni/tags
We are not asking the userbase to comb through the history.  This due diligence is done with code for the past 6 years (and counting).  The range back in time of well-tagged code seems to extend back far enough for anything that would be broadly relevant today.

The divergence of opinion comes with very old code.  It does not seem broadly useful to go back and re-tag superold code.  Again, if you have some specific version number cases for the too-old-to-have-been-autotagged code, we have offered to try and help.

**Comment by dmwelch** [comment]
My original post has the version I need.  I'd appreciate your helpfulness tagging that one.

**Comment by mrneont** [comment]
@dmwelch 

That tag ("AFNI_legacy_11.3.82") should now be created for that commit:
https://github.com/afni/afni/releases/tag/AFNI_legacy_11.3.82

The major.minor.micro numbering reflects:  year.quarter.[days since start of quarter], because the commit date was Dec 21, 2011.

Hope that works fine---if you confirm that, then I can close this issue.

And then please just let us know if you have any other commit/versions that you would like tagged (e.g., opening an issue and providing the commit hash, as here), and that should be doable.

**Comment by mrneont** [comment]
OK, it has been a week with no feedback on this.  I will assume that the tag sufficed, and I am closing this issue.

And if you would like other specific versions tagged, just let us know.
