### ISSUE TITLE
Afni website not accessible

### ISSUE THREAD

**Issue by felixsc1** [afni/afni#26]
There seems to be a problem with https://afni.nimh.nih.gov
Depending on the browser I get messages like "This site can’t provide a secure connection" and "ERR_SSL_PROTOCOL_ERROR" on every computer. 

While the site is not accessible, is there an alternative source to download the AFNI binaries (for Mac OS)?

**Comment by afni-rickr** [comment]
There was a problem with IPv6 that was resolved this morning.
Sorry for the trouble.
