### ISSUE TITLE
Update dcm2niix_afni

### ISSUE THREAD

**Issue by neurolabusc** [afni/afni#272]
The version of dcm2niix distributed with AFNI is from [Fall 2018](https://github.com/afni/afni/blob/25e77d564f2c67ff480fa99a7b8e48ec2d9a89fc/src/crorden/dcm2niix_console/nii_dicom.h#L46). dcm2niix is typically updated twice a year (spring and fall), so the latest stable release is [Spring 2021](https://github.com/rordenlab/dcm2niix/releases). AFNI users may [benefit from having a recent version](https://github.com/rordenlab/dcm2niix/issues/514).

**Comment by afni-rickr** [comment]
Updating, thanks!
