### ISSUE TITLE
3dTshift should set toffset field for NIfTI based on -tzero or -slice parameter

### ISSUE THREAD

**Issue by effigies** [afni/afni#297]
The point of applying slice timing correction is to ensure that the entire volume has the same effective sampling time, but that sampling time is the same as the original series only if corrected to the first acquired slice. To allow correct interpretation, 3dTshift should set `toffset`.

xref https://github.com/nipreps/fmriprep/issues/2477

**Comment by afni-rickr** [comment]
Hi @effigies.  Sorry for being slow, I am doing this now.  Thanks for the suggestion.

**Comment by afni-rickr** [comment]
Hi @effigies.  BTW, this toffset propagation did go into 3dTshift and is in the current binaries.  Thanks again.
