### ISSUE TITLE
Which AFNI image to pull

### ISSUE THREAD

**Issue by butellyn** [afni/afni#300]
Hello! I would like to get started with AFNI through using the Docker image. I noticed in the [instructions](https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/container.html) that you say to pull `afni/afni`, but this image no longer exists. Instead, I pulled `afni/afni_dev_base`. The pull was successful, but when I launched the container, key programs such as `3dvolreg` could not be found. I imagine that there are a few lines missing from the bashrc. Should I run any of the system setup commands? I assumed that all of those would have been taken care of in the image building stage, but that may not be the case. Or should I use a different image? Thanks!

**Comment by leej3** [comment]
The image you pulled is a base image used for the two images that contain the full build of afni: `afni_make_build` and `afni_cmake_build`

If you are developing I would recommend `afni/afni_cmake_build`. You can mount the source or build directories from your local file system and so take advantage of the dependency encapsulation without losing work etc. (though I believe if you use vscode to work with the code inside the container you don't even need to do that). There are various other advantages to using the cmake build. 
With that said a truer match to the binaries distributed by the team is in the `afni/afni_make_build image`. i.e. it uses the same make build system maintained by the team but just drives the build in a docker container: https://github.com/afni/afni/blob/master/.docker/make_build.dockerfile. If you are hoping to make use of AFNI as an end-user this is likely the better image to use.

Both of these are built  as [part of the CI](https://github.com/afni/afni/blob/master/.circleci/config.yml#L331) if you want to check out how the sausage is made.

**Comment by mrneont** [comment]
Hi @butellyn 

I know this is quite late, but just I noticed now this issue was never closed.  

Has the problem been resolved?  We have recently updated our Docker instructions, which should help:
https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/container.html
(and help any future users investigating this, too.)

Apologies about the delay.

-pt

**Comment by butellyn** [comment]
It works now! The documentation helped. Thank you

**Comment by mrneont** [comment]
Great, glad that sorted it, and thanks for letting us know.
