### ISSUE TITLE
** FATAL ERROR: no datasets found!

### ISSUE THREAD

**Issue by teachmepleasee** [afni/afni#306]
While running the @animal_warper command. It gives the following error - 

++ Making 'base' abbrev:
   ... NO-DSET
 --> NO-DSET
++ 3dcopy: AFNI version=AFNI_20.3.05 (Jan  7 2021) [64-bit]
** FATAL ERROR: no datasets found!

THIS IS THE OUTPUT FROM MY "animal_outs" file. When I run it on a local WSL, the "Base Space" gets correctly filled as NMT_v2.0. However, when I ran on SSH, it says "NO-DSET". Please give your suggestions, if any.

# List of inputs and outputs from @animal_warper
AFNI package                          : linux_centos_7_64
AFNI version number                   : AFNI_20.3.05
@animal_warper ver                    : 3.1

Input dset (orig)                     : mysample-001.nii.gz
Base dset (templ)                     : NMT_v2.0_sym_05mm
Base space                            : NO-DSET
Atlas dset(s)                         : 
Final orig space (center_out)         : native

**Comment by mrneont** [comment]
Hi-

When you say "running it on ssh", does that mean that you ssh'ed into another computer and executed the same command there?  

If so, I guess that the NMT data has not been downloaded on that other system that you are ssh'ing into. 

Did you download the NMT onto your WSL using one of the MACAQUE_DEMO or MACAQUE_DEMO_REST tutorials, or via direct download?  You would need to similarly put that data on the other system.

--pt

**Comment by teachmepleasee** [comment]
Hi.

Yes. I have remote access to a cluster that I SSH onto. I have downloaded the NMT data onto the storage space that I have in that cluster using the command,
**@Install_NMT -nmt_ver 2.0 -sym asym**

Following this, a folder named **NMT_v2.0_sym** was downloaded into that storage with several other folder in it given by,
CustomAtlases.niml  NMT_v2.0_sym       NMT_v2.0_sym_env.csh  NMT_v2.0_sym_surfaces  tables_CHARM  tables_SARM
NMT_changelog.txt   NMT_v2.0_sym_05mm  NMT_v2.0_sym_fh       readme.md              tables_D99

From the home directory, when I give the command:
**@animal_warper -input samplemri.nii.gz  -base NMT_v2.0_sym/NMT_v2.0_sym_fh/NMT_v2.0_sym_fh.nii.gz**,

It recognizes the input and base MRIs and creates a folder named "aw_results". But after that, it hits the error - "** FATAL ERROR: no datasets found!" and closes.

For my local WSL (Ubuntu Linux 18), I had also used the same command to download the NMT_2.0 data (@Install_NMT -nmt_ver 2.0 -sym asym). Do I need to download NMT data using only MACAQUE_DEMO or MACAQUE_DEMO_REST tutorials?

Thank you

**Comment by mrneont** [comment]
There are both symmetric and asymmetric versions of NMTv2.

Your download command is getting the asymmetric one, because of the "-sym asym".  The directories/files there all have names like:
* NMT_v2.0_asym
* NMT_v2.0_asym_fh
* NMT_v2.0_asym_fh_SS.nii.gz
... etc.  Note the "asym" part of the name.

In your script, you are asking for the symmetric version of files, because you are using the "_sym_" part of the name.

If you actually want to be using the symmetric version of the templates and atlases, then you can download it with:
```
@Install_NMT -nmt_ver 2.0 -sym sym
```

... and that should match your script.  Or, alternatively, change your script file names to use the asymmetric format you have downloaded.

--pt

**Comment by teachmepleasee** [comment]
Hi.

I am so sorry. I dropped in the wrong command here. I had given the **@Install_NMT -nmt_ver 2.0 -sym sym** and not the asym one. Sorry for the goof up.

Following this, a folder named NMT_v2.0_sym was downloaded into that storage with several other folder in it given by,
CustomAtlases.niml NMT_v2.0_sym NMT_v2.0_sym_env.csh NMT_v2.0_sym_surfaces tables_CHARM tables_SARM
NMT_changelog.txt NMT_v2.0_sym_05mm NMT_v2.0_sym_fh readme.md tables_D99

These are the files downloaded after giving Install_NMT command.  

From the home directory, when I give the command:
@animal_warper -input samplemri.nii.gz -base NMT_v2.0_sym/NMT_v2.0_sym_fh/NMT_v2.0_sym_fh.nii.gz,

It recognizes the input and base MRIs and creates a folder named "aw_results". But after that, it hits the error - "** FATAL ERROR: no datasets found!" and closes.

For my local WSL (Ubuntu Linux 18), I had also used the same command to download the NMT_2.0 data (@Install_NMT -nmt_ver 2.0 -sym sym). 

So my question is, Do I need to download NMT data using only MACAQUE_DEMO or MACAQUE_DEMO_REST tutorials?

Thank you

**Comment by mrneont** [comment]
Hi-

The macaque demo install by default doesn't do anything special, besides download things.  (You can add the NMT directory location to your AFNI environment variables in your ~/.afnirc directory, so that the template+atlas can be used for ``whereami`` functionality in the GUI and command line, but that should be separate.) 

I just tried running the following:
```
@Install_NMT -nmt_ver 2.0 -sym sym

@animal_warper -input anat-sub-000.nii.gz  -base NMT_v2.0_sym/NMT_v2.0_sym_fh/NMT_v2.0_sym_fh.nii.gz
```

... and things were fine.  This was using both the current version of AFNI, as well as getting the older @animal_warper (v3.1). 

If you copy+paste each of the following from where you are running your command right now, what is the output:

`\ls NMT_v2.0_sym/NMT_v2.0_sym_fh/NMT_v2.0_sym_fh.nii.gz`

`@FindAfniDsetPath -full_path -append_file NMT_v2.0_sym/NMT_v2.0_sym_fh/NMT_v2.0_sym_fh.nii.gz`

?

--pt

**Comment by teachmepleasee** [comment]
Hi.

1. `\ls NMT_v2.0_sym/NMT_v2.0_sym_fh/NMT_v2.0_sym_fh.nii.gz`

For the above, I get `NMT_v2.0_sym/NMT_v2.0_sym_fh/NMT_v2.0_sym_fh.nii.gz`

2. `@FindAfniDsetPath -full_path -append_file NMT_v2.0_sym/NMT_v2.0_sym_fh/NMT_v2.0_sym_fh.nii.gz`

For the second one, I get an error saying - 
```
ParseName: Command not found.
ParseName: Command not found.
/home/gurumk/NMT_v2.0_sym/NMT_v2.0_sym_fh/
```

P.S. gurumk is my username.


And yes, in the initial error of  **** FATAL ERROR: no datasets found!**,  I remember seeing the same ParseName error.

Thank you.

**Comment by mrneont** [comment]
OK, so thaaaat this the problematic error.  The ``\ls ...`` command shows that the file is really in the correct/knowable place.  The  ``@FindAfniDsetPath`` script *should* be returning that path location---but it ain't.  (We use the ``@Find*`` command because it is more general, if AFNI environment variables are used to point to directories.)   So, the real question is: why is ``@FindAfniDsetPath`` not working there?

Can you run the system check on that computer:
`afni_system_check.py -check_all`
... and paste its outputs here? 

Also, are you able to update AFNI on that computer (or does someone else administer it, and would need to do so?)?  I wonder if there was a temporary problem that has been subsequently fixed (because when I run the modern or older @animal_warper on my Ubuntu, both work;  but I didn't go back and recreate that full set of binaries from The Past).

--pt

**Comment by teachmepleasee** [comment]
Hi.

There is a huge list of answers coming up. I 

```
[gurumk@beluga3 ~]$ afni_system_check.py -check_all
-------------------------------- general ---------------------------------
architecture:         64bit ELF
system:               Linux
release:              3.10.0-1160.41.1.el7.x86_64
version:              #1 SMP Tue Aug 31 14:52:47 UTC 2021
distribution:         CentOS Linux 7.9.2009 Core
number of CPUs:       40
apparent login shell: bash
shell RC file:        .bashrc (exists)

--------------------- AFNI and related program tests ---------------------
which afni           : /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Compiler/gcc9/afni/20.3.05/afni
afni version         : Precompiled binary linux_centos_7_64: Jan  7 2021
                     : AFNI_20.3.05 'Vespasian'
AFNI_version.txt     : AFNI_20.3.05, linux_centos_7_64, Jan 07 2021
which python         : /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.7.9/bin/python
python version       : 3.7.9
which R              : /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/r/4.0.2/bin/R
R version            : R version 4.0.2 (2020-06-22) -- "Taking Off Again"
which tcsh           : /cvmfs/soft.computecanada.ca/gentoo/2020/bin/tcsh

instances of various programs found in PATH:
    afni    : 1   (/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Compiler/gcc9/afni/20.3.05/afni)
    R       : 1   (/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/r/4.0.2/bin/R)
    python  : 3
      /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.7.9/bin/python3.7
      /cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin/python-exec2c
      /usr/bin/python2.7
    python2 : 2
      /cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin/python-exec2c
      /usr/bin/python2.7
    python3 : 3
      /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.7.9/bin/python3.7
      /cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin/python-exec2c
      /usr/bin/python3.6


testing ability to start various programs...
    afni                 : success
    suma                 : success
    3dSkullStrip         : FAILURE
        /bin/sh: 3dSkullStrip: command not found
    uber_subject.py      : success
    3dAllineate          : success
    3dRSFC               : success
    SurfMesh             : FAILURE
        /bin/sh: SurfMesh: command not found
    3dClustSim           : success
    3dMVM                : success

checking for R packages...
    rPkgsInstall -pkgs ALL -check : FAILURE

        oo Warning:
           These packages are not installed on the computer: afex!
        These packages are not installed on the computer: phia!
        These packages are not installed on the computer: paran!
        These packages are not installed on the computer: brms!
        These packages are not installed on the computer: corrplot!
        These packages are not installed on the computer: metafor!


R RHOME : /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/r/4.0.2/lib64/R

checking for $HOME files...
    .afnirc                   : missing
    .sumarc                   : missing
    .afni/help/all_progs.COMP : missing

------------------------------ python libs -------------------------------
** failed to load module PyQt4
-- PyQt4 is no longer needed for an AFNI bootcamp

** failed to load module matplotlib.pyplot
-- matplotlib.pyplot is not required, but is desirable

-------------------------------- env vars --------------------------------
PATH = /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Compiler/gcc9/afni/20.3.05:/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.7.9/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/expat/2.2.9/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/nodejs/12.16.1/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Compiler/gcc9/fftw/3.3.8/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Compiler/gcc9/netcdf/4.7.4/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/mariadb-connector-c/3.1.7/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Compiler/gcc9/hdf5/1.10.6/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Compiler/gcc9/gsl/2.6/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/qt/5.12.8/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/r/4.0.2/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/java/13.0.2:/cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/java/13.0.2/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Compiler/gcc9/openmpi/4.0.3/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/libfabric/1.10.1/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/ucx/1.8.0/bin:/cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/gcccore/9.3.0/bin:/cvmfs/soft.computecanada.ca/easybuild/bin:/cvmfs/soft.computecanada.ca/custom/bin:/cvmfs/soft.computecanada.ca/gentoo/2020/usr/sbin:/cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin:/cvmfs/soft.computecanada.ca/gentoo/2020/sbin:/cvmfs/soft.computecanada.ca/gentoo/2020/bin:/cvmfs/soft.computecanada.ca/custom/bin/computecanada:/opt/software/slurm/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/home/gurumk/.local/bin:/home/gurumk/bin

PYTHONPATH = /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.7.9/easybuild/python:/cvmfs/soft.computecanada.ca/easybuild/python/site-packages:/cvmfs/soft.computecanada.ca/custom/python/site-packages

R_LIBS = /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Compiler/gcc9/r-bundle-bioconductor/3.12

LD_LIBRARY_PATH =
DYLD_LIBRARY_PATH =
DYLD_FALLBACK_LIBRARY_PATH =

------------------------------ data checks -------------------------------
data dir : missing AFNI_data6
data dir : missing AFNI_demos
data dir : missing suma_demo
data dir : missing afni_handouts
atlas    : did not find TT_N27+tlrc

------------------------------ OS specific -------------------------------
which yum            : /usr/bin/yum
yum version          : 3.4.3


=========================  summary, please fix:  =========================
*  just be aware: login shell 'bash', but our code examples use 'tcsh'
*  AFNI programs show FAILURE
*  missing R packages (see rPkgsInstall)
*  please run: cp /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Compiler/gcc9/afni/20.3.05/AFNI.afnirc ~/.afnirc
*  please run: "suma -update_env" for .sumarc
*  please run: apsearch -update_all_afni_help
*  insufficient data for AFNI bootcamp
*  possibly missing atlases
```


So yes. The only available AFNI version on this cluster is 20.3.05. And the @animal_warper version being chosen is 3.1.

Hope these details suffice. Also, I see that `.afnirc ` is missing!! 

Thank you!

**Comment by mrneont** [comment]
Howdy-

These items are not problems per se, but you can run these commands there (to populate default environment variables for AFNI and SUMA, and to have autocompletion of program options in the terminal, respectively):
```
cp /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Compiler/gcc9/afni/20.3.05/AFNI.afnirc ~/.afnirc
suma -update_env
apsearch -update_all_afni_help
```

The problem part is the program failure---specifically, the non-R ones like 3dSkullStrip and SurfMesh.  I am guessing that you are missing a dependency on this system.  

Do you have admin rights on this system?  (That is, can you run ``sudo ...`` commands, like ``sudo ls``?)

The CentOS dependencies are listed here:
https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_Fed_RH.html#install-prerequisite-packages

Specifically, these commands:
```
sudo yum install -y epel-release
sudo yum install -y tcsh libXp openmotif gsl xorg-x11-fonts-misc       \
                    PyQt4 R-devel netpbm-progs gnome-tweak-tool ed     \
                    libpng12 xorg-x11-server-Xvfb firefox
sudo yum update -y
```

Can you run those, or is it a separately administered system?

--pt

**Comment by teachmepleasee** [comment]
Hello!

The point is I do not have admin rights on this system and I can't run any of the` sudo` commands :( I tried running those `sudo yum` commands on my system and it told me that I don't have the access to the `sudo` command.

Is there any other way to bring back the missing dependencies?

Thank you!

**Comment by mrneont** [comment]
Howdy-

Sure, I understand.  That is common on administered systems (that users don't have admin rights).

You will have to ping that system's administrators to ask them to check those missing dependencies, and to ask if they can run those.  (It might be nice to ask if they could update the AFNI, there, too, since it is nearly a year old now.)

The list of required dependencies is given, and they will know when they have provided the missing one when the `afni_system_check.py -check_all` does not show failures for 3dSkullStrip and SurfMesh (the R programs are a separate issue).

--pt

**Comment by teachmepleasee** [comment]
Hello.

Thank you so much for your assistance. I shall ask the system's administrators to check for missing dependencies and also if possible, an AFNI update.

Thank you once again for taking out time and being so kind! :)

**Comment by mrneont** [comment]
Sure thing---hope they can update things there easily.

--pt

**Comment by mrneont** [comment]
Hi, @teachmepleasee --

Just checking in on this.  Were your system administrators able to update things?

Also, should I close this issue here, and if something else comes up you can make a new issue or ask a question on the Message Board:
https://afni.nimh.nih.gov/afni/community/board/list.php?1
?

--pt

**Comment by teachmepleasee** [comment]
Hi. Yes, the system has been updated. 

Thank you for your help!!
