### ISSUE TITLE
cannot find the source code for 3dSkullStrip

### ISSUE THREAD

**Issue by nikinbaidarr** [afni/afni#335]
I could not install some of the programs so I decided to take a look at the source code. But I couldn't even find the 3dSkullStrip program. Where can I find it?

**Comment by mrneont** [comment]
Howdy-

The main code for that program is lurking in:
SUMA/SUMA_3dSkullStrip.c

But if you have questions about setup, then probably describing the OS you have, and the output of:
```
afni_system_check.py -check_all
```
on the [AFNI Message Board](https://afni.nimh.nih.gov/afni/community/board/list.php?1) would be the best way to troubleshoot that.

Installation instructions for various OSs are here:
https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/main_toc.html
... though those are for running the pre-compiled binaries.  If you want to be able to *compile* the code on a particular OS, then let us know your OS and we can discuss that more here.

**Comment by mrneont** [comment]
OK, I don't know much about Arch Linux, but we recently had a discussion with @liamtimms, who maintains an AFNI package built there.

In fact, googling around a bit, I think you might have had some earlier discussions on their Message Board:
https://aur.archlinux.org/packages/afni/

A problem had come up with building AFNI there, but I believe a recent Issue discussion here fixed it:
https://github.com/afni/afni/issues/330

So maybe you can get the binaries from there directly?

**Comment by mrneont** [comment]
I am a bit confused.  So, when the system check says you are using "linux_openmp_64", which is the name of a binaries package we distribute, did *not* actually come from our build, but instead from the Arch Linux folks?  Having the same name is confusing for troubleshooting...  If that is the current situation, I might suggest the name "linux_arch" for the other package, for clarity.

I am also paying more attention that your error message is that some commands are not *found*, which I am not used to seeing:
        /bin/sh: line 1: suma: command not found
That means the build failed for them, not just that you are missing a dependency.

I might suggest trying getting the openmp binaries from the AFNI distribution, which should have all the programs at least built:
```
tcsh @update.afni.binaries -package linux_openmp_64 -do_extras
```
I assume this will work to replace the previous binaries with the linux_openmp_64 ones we build, because we do have a more recent version available.

Do you want to try that, and see if the programs exist?

**Comment by nikinbaidarr** [comment]
> So, when the system check says you are using "linux_openmp_64", which is the name of a binaries package we distribute, did _not_ actually come from our build, but instead from the Arch Linux folks?

Not really. No As explained [here](https://wiki.archlinux.org/title/Arch_User_Repository), Arch only provides PKGBUILDs for packages so that they can be directly complied from source with makepkg. So those binaries actually were complied on my machine and didn't come from neither your build nor from the Arch folks.
 

> I might suggest trying getting the openmp binaries from the AFNI distribution, which should have all the programs at least built:
> 
> ```
> tcsh @update.afni.binaries -package linux_openmp_64 -do_extras
> ```
> Do you want to try that, and see if the programs exist?

I tried this and it pretty much worked. Although I did have to install some missing libraries ligjpeg, and libgsl. I also had to create a couple symlinks.
Here are the actual steps to reproduce: (at least on my machine):
```
@update.afni.binaries -package linux_openmp_64 -do_extras
pacman -S libpng12 libjpeg
yay -S gsl
cd /usr/lib64
ln -sf libgslcblas.so.0.0.0 ligbsl.so.0
ln -sf libjpeg.so.8.2.2 libjpeg.so.62
```
Now the installation is working fine. Here's the updated output of `afni_system_check.py -check_all | less`:

```
testing ability to start various programs...
    afni                 : success
    suma                 : success
    3dSkullStrip         : success
    uber_subject.py      : success
    3dAllineate          : success
    3dRSFC               : success
    SurfMesh             : success
    3dClustSim           : success
    3dMVM                : success

checking for R packages...
    rPkgsInstall -pkgs ALL -check : success

...

** failed to load module PyQt4
-- PyQt4 is no longer needed for an AFNI bootcamp

++ module loaded: matplotlib.pyplot
   module file : /home/nikin/.local/lib/python3.10/site-packages/matplotlib/pyplot.py
   matplotlib version : 3.5.1
...
=========================  summary, please fix:  =========================
*  just be aware: login shell 'bash', but our code examples use 'tcsh'
*  please run: "suma -update_env" for .sumarc
*  insufficient data for AFNI bootcamp
   (see "Prepare for Bootcamp" on install pages)
```

Closing this issue now. Thank you so much for your time and effort for looking into this. I am really grateful. Thank you so much!

**Comment by afni-rickr** [comment]
@nikinbaidarr You should be approved for the AFNI message board now, too.  Thanks.

**Comment by nikinbaidarr** [comment]
> @nikinbaidarr You should be approved for the AFNI message board now, too. Thanks.

Nope not really. Haven't received an email nor can I log in.

**Comment by mrneont** [comment]
I am a bit confused;  it looked like you had 2 email registrations, and I think both were approved earlier this morning.

Could you please check your spam folder?

**Comment by nikinbaidarr** [comment]
> Could you please check your spam folder?
No nothing in my spam. Should I request another registration?

**Comment by mrneont** [comment]
I guess let's try that again, yes.  Sorry for the hassle.

**Comment by nikinbaidarr** [comment]
> I guess let's try that again, yes. Sorry for the hassle.

I tried registering again it said "The name you entered is already registered by another user. If you are that user, please login. Otherwise, please use another name." But I couldn't login so I requested for a new password but didn't receive any email.

**Comment by afni-rickr** [comment]
@nikinbaidarr I have sent you direct email on this.  That will make it easy to resolve.
