### ISSUE TITLE
Fix IsoSurface winding errors

### ISSUE THREAD

**Issue by neurolabusc** [afni/afni#342]
[IsoSurface](https://afni.nimh.nih.gov/pub/dist/doc/program_help/IsoSurface.html) uses [a C port of Thomas Lewiner's Marching Cubes’ cases with topological guarantees](http://thomas.lewiner.org/pdfs/marching_cubes_jgt.pdf). However, the implementation generates some triangles with incorrect [triangle winding](https://cmichel.io/understanding-front-faces-winding-order-and-normals). You can observe this by running the command 

```
IsoSurface -input bet.nii.gz -isorange 128 255 -o_PLY isorange64_255
```

and displaying the results with a tool that discriminates between front and back faces like MeshLab or Surfice. These artifacts also frustrate mesh simplification routines. This appears to reflect using Lewiner's tables dated 13/07/2002, whereas [other C++ implementation](https://github.com/nci/drishti) use tables dated 12/08/2002. 

I have created a [repository](https://github.com/neurolabusc/LewinerMarchingCubes) with two [releases](https://github.com/neurolabusc/LewinerMarchingCubes/releases): 1.0.20020713 is the AFNI code, while 1.0.20020812 updates the tables. Updating the AFNI files MarchingCubes.h, MarchingCubes.c and LookUpTable.h should resolve the issue. As a bonus, if you compile MarchingCubes.c with the directive `-DMC_SELF_TEST` you will create a standalone executable (when you integrate this into AFNI you can delete the [main.c demo and update that make file](https://github.com/afni/afni/tree/25e77d564f2c67ff480fa99a7b8e48ec2d9a89fc/src/SUMA/MarchingCubes)). 

Therefore, you can check the old implementation:
```
git clone --depth 1 --branch 1.0.20020713 https://github.com/neurolabusc/LewinerMarchingCubes
cd LewinerMarchingCubes
make
./MarchingCubes bet.nii 128
```

And the patched version:
```
git clone --depth 1 --branch 1.0.20020812 https://github.com/neurolabusc/LewinerMarchingCubes
cd LewinerMarchingCubes
make
./MarchingCubes bet.nii 128
```

Here is a comparison of the original and updated output seen with Surfice:

![MC_winding2](https://user-images.githubusercontent.com/8930807/151400326-ed168bfb-fac7-4970-91dc-8f5ec15a8af8.png)

**Comment by mrneont** [comment]
Just to note, this is still on our radar, hopefully quite soon in the new year...

**Comment by afni-rickr** [comment]
Hi @neurolabusc.  We did merge this, see #480.  Thanks again.

**Comment by neurolabusc** [comment]
Great!
