### ISSUE TITLE
is 3dFourier depreciated?

### ISSUE THREAD

**Issue by nikinbaidar** [afni/afni#351]
I had to work with some older scripts, in one of which the `3dFourier` function/command was used. For the man page for `3dFourier` it was suggested to use `3dBandpass` instead. So, is `3dFourier` depreciated now, if so, is there an official reference for this?

**Comment by mrneont** [comment]
Yes, it's deprecated.  

If you look in the comprehensive history:
https://afni.nimh.nih.gov/pub/dist/doc/misc/history/index.html
...for '3dFourier', the most recent mention (closest to the top of the page) states the deprecation.  The deprecation date is: 25 Aug 2020.

We also announced it on the AFNI Digest, which you can sign up for here (highly recommended for all AFNI users):
https://afni.nimh.nih.gov/afni/community/board/read.php?1,154890,154890

--pt

**Comment by mrneont** [comment]
Also, in the Classified program list:
https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/educational/classified_progs.html
.... there is a section specifically for retired/deactivated programs:
https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/educational/classified_progs.html#retired-no-longer-in-the-build

Though, I discovered today that page hadn't been updating for a while---I have fixed it now, so it reflects the (mostly) current state of being.

**Comment by nikinbaidar** [comment]
Thank you! Exactly what I was looking for.
