### ISSUE TITLE
Should not ``3dWarp -deoblique`` followed by ``3dAllineate`` give the same result as just ``3dAllineate``?

### ISSUE THREAD

**Issue by oesteban** [afni/afni#353]
This follows up on my difficulties with applying affines when either reference or moving images are not aligned with the cardinal axes -i.e., image array's axes- (#116, #129).

I have created an image (a binary brain mask, in this case) and modified its x-forms to make it look oblique to the eyes of AFNI, file `mask.nii.gz`:
```
$ 3dinfo mask.nii.gz 
++ 3dinfo: AFNI version=AFNI_21.2.00 (Jul  8 2021) [64-bit]

Dataset File:    /tmp/pytest-of-oesteban/pytest-300/test_apply_linear_transform_af0/mask.nii.gz
Identifier Code: NII_aXsGAcbPD_o15sXUyPhMsQ  Creation Date: Tue Feb 22 15:55:26 2022
Template Space:  ORIG
Dataset Type:    Anat Bucket (-abuc)
Byte Order:      LSB_FIRST {assumed} [this CPU native = LSB_FIRST]
Storage Mode:    NIFTI
Storage Space:   213,864 (214 thousand) bytes
Geometry String: "MATRIX(-2.749997,0.00275,-0.00275,76.98479,-0.002986,-2.738868,0.247166,83.6692,-0.002492,0.247169,2.738869,-83.40569):57,67,56"
Data Axes Tilt:  Oblique (5.157 deg. from plumb)
Data Axes Approximate Orientation:
  first  (x) = Left-to-Right
  second (y) = Posterior-to-Anterior
  third  (z) = Inferior-to-Superior   [-orient LPI]
R-to-L extent:   -77.015 [R] -to-    76.985 [L] -step-     2.750 mm [ 57 voxels]
A-to-P extent:   -97.831 [A] -to-    83.669 [P] -step-     2.750 mm [ 67 voxels]
I-to-S extent:   -83.406 [I] -to-    67.844 [S] -step-     2.750 mm [ 56 voxels]
Number of values stored at each pixel = 1
  -- At sub-brick #0 '?' datum type is byte
```

I also generate a text-file with an affine transformation matrix (6 dof) called `M.afni`, with contents:
```
# 3dvolreg matrices (DICOM-to-DICOM, row-by-row):
0.999999	-0.000999999	-0.001	-4	0.00140494	0.621609	0.783327	-2	-0.000161717	-0.783327	0.62161	-1
```

If I run 
```
3dAllineate -base mask.nii.gz -input mask.nii.gz -prefix direct.nii.gz -1Dmatrix_apply M.afni -final NN
```
I get a file `direct.nii.gz` with the following specs:
```
$ 3dinfo direct.nii.gz 
++ 3dinfo: AFNI version=AFNI_21.2.00 (Jul  8 2021) [64-bit]

Dataset File:    /tmp/pytest-of-oesteban/pytest-300/test_apply_linear_transform_af0/direct.nii.gz
Identifier Code: XYZ_I5h0HiUSa2q-7UtkBf1N3g  Creation Date: Tue Feb 22 15:34:59 2022
Template Space:  ORIG
Dataset Type:    Anat Bucket (-abuc)
Byte Order:      LSB_FIRST {assumed} [this CPU native = LSB_FIRST]
Storage Mode:    NIFTI
Storage Space:   213,864 (214 thousand) bytes
Geometry String: "MATRIX(-2.75,0,0,76.98479,0,-2.75,0,83.6692,0,0,2.75,-83.40569):57,67,56"
Data Axes Tilt:  Plumb
Data Axes Orientation:
  first  (x) = Left-to-Right
  second (y) = Posterior-to-Anterior
  third  (z) = Inferior-to-Superior   [-orient LPI]
R-to-L extent:   -77.015 [R] -to-    76.985 [L] -step-     2.750 mm [ 57 voxels]
A-to-P extent:   -97.831 [A] -to-    83.669 [P] -step-     2.750 mm [ 67 voxels]
I-to-S extent:   -83.406 [I] -to-    67.844 [S] -step-     2.750 mm [ 56 voxels]
Number of values stored at each pixel = 1
  -- At sub-brick #0 '?' datum type is byte:            0 to             1

----- HISTORY -----
[oesteban@hos65851: Tue Feb 22 15:34:59 2022] {AFNI_21.2.00:linux_ubuntu_16_64} 3dAllineate -base /tmp/pytest-of-oesteban/pytest-300/test_apply_linear_transform_af0/mask.nii.gz -input /tmp/pytest-of-oesteban/pytest-300/test_apply_linear_transform_af0/mask.nii.gz -prefix /tmp/pytest-of-oesteban/pytest-300/test_apply_linear_transform_af0/direct.nii.gz -1Dmatrix_apply /tmp/pytest-of-oesteban/pytest-300/test_apply_linear_transform_af0/M.afni -final NN
```

If I understand correctly the logged outputs of ``3dAllineate``, the images' axes are reoriented to be aligned with the cardinal axes internally. Also, if I understand correctly, this process should be equivalent to running:

```
3dWarp -deoblique -NN -prefix mask_deob.nii.gz mask.nii.gz
3dAllineate -base direct.nii.gz -input mask_deob.nii.gz -prefix indirect.nii.gz -1Dmatrix_apply M.afni -final NN
```

I'm using `direct.nii.gz` to obtain the equivalent grid of method 1 at the output, because for some reason the output of `3dWarp -deoblique` is slightly different to that `direct.nii.gz` file generated with `3dAllineate`:

```
$ 3dinfo mask_deob.nii.gz 
++ 3dinfo: AFNI version=AFNI_21.2.00 (Jul  8 2021) [64-bit]

Dataset File:    /tmp/pytest-of-oesteban/pytest-300/test_apply_linear_transform_af0/mask_deob.nii.gz
Identifier Code: XYZ_lZPpi5xNEDXHOukKCF1-BA  Creation Date: Tue Feb 22 15:37:57 2022
Template Space:  ORIG
Dataset Type:    Anat Bucket (-abuc)
Byte Order:      LSB_FIRST {assumed} [this CPU native = LSB_FIRST]
Storage Mode:    NIFTI
Storage Space:   258,912 (259 thousand) bytes
Geometry String: "MATRIX(2.75,0,0,-78.375,0,2.75,0,-97.62502,0,0,2.75,-83.875):58,72,62"
Data Axes Tilt:  Plumb
Data Axes Orientation:
  first  (x) = Right-to-Left
  second (y) = Anterior-to-Posterior
  third  (z) = Inferior-to-Superior   [-orient RAI]
R-to-L extent:   -78.375 [R] -to-    78.375 [L] -step-     2.750 mm [ 58 voxels]
A-to-P extent:   -97.625 [A] -to-    97.625 [P] -step-     2.750 mm [ 72 voxels]
I-to-S extent:   -83.875 [I] -to-    83.875 [S] -step-     2.750 mm [ 62 voxels]
Number of values stored at each pixel = 1
  -- At sub-brick #0 '?' datum type is byte:            0 to             1

----- HISTORY -----
[oesteban@hos65851: Tue Feb 22 15:37:57 2022] {AFNI_21.2.00:linux_ubuntu_16_64} 3dWarp -verb -deoblique -NN -prefix mask_deob.nii.gz mask.nii.gz
```

When I open (with the Mango viewer, which correctly interprets x-form headers) both `direct.nii.gz` and `indirect.nii.gz`, there is an obvious translation between the files. My expectation was that there should be none (other than interpolation errors that could happen), because `3dWarp -deoblique` should apply just a reslicing of the image array with identity transformation of the physical coordinates (i.e., the data remains in the same spatial location, but the data array is now aligned with the physical coordinate axes). The fact that the output grid is different should also be independent of the transform, as the output grid defines where we are going to sample through the transformation that is the same in both scenarios.

What am I misunderstanding about the operation of `3dAllineate`? Why the difference in size (and origin) between the output of `3dAllineate` and `3dWarp -deoblique`?

/ cc @effigies @matthew-brett

**Comment by oesteban** [comment]
Paging @afni-dglen for his always helpful wisdom :)

**Comment by mrneont** [comment]
Hi, Oscar-

I'm no @afni-dglen , but I will take a crack at this.

There are 2 ways AFNI programs deoblique (sadly, the same term):
+ `3dWarp -deoblique ... ` *applies* the obliquity information
+ `3drefit -deoblique ...` *purges* the obliquity information

Viewing an oblique dataset in the GUI behaves "as if" the dset had been 3drefit-deobliqued (the obliquity info was purged).  3dAllineate also behaves the same---it essentially ignores the information.

In your "indirect" case, you are 3dWarp-deoblique'ing the dset, which is why that doesn't appear to be the same thing.

So, let's look at 2 indirect cases, with 3dWarp-deoblique'ing (your case) and 3drefit-deoblique'ing:

```
#!/bin/tcsh

set mask  = MMM.nii.gz
set aff1D = mat.aff12.1D

# ------------------------------------------------------------------------
# apply 3dAllineate on original dset, which has obliquity

3dAllineate \
    -overwrite \
    -base            ${mask} \
    -input           ${mask} \
    -prefix          direct.nii.gz  \
    -1Dmatrix_apply  ${aff1D}       \
    -final           NN

# ------------------------------------------------------------------------
# first deoblique with 3dWarp ('apply' obliquity info; regrid), 
# then 3dAllineate

3dWarp \
    -overwrite \
    -deoblique \
    -prefix MMM_warpdeob.nii.gz  \
    MMM.nii.gz

3dAllineate \
    -overwrite \
    -base            direct.nii.gz \
    -input           MMM_warpdeob.nii.gz \
    -prefix          indirect_warpdeob.nii.gz \
    -1Dmatrix_apply  ${aff1D}  \
    -final           NN

# ------------------------------------------------------------------------
# first deoblique with 3drefit ('purge' obliquity info; no regrid),
# then 3dAllineate

3dcopy \
    -overwrite \
    MMM.nii.gz \
    MMM_refitdeob.nii.gz

3drefit \
    -deoblique \
    MMM_refitdeob.nii.gz

3dAllineate \
    -overwrite \
    -base            direct.nii.gz \
    -input           MMM_refitdeob.nii.gz \
    -prefix          indirect_refitdeob.nii.gz \
    -1Dmatrix_apply  ${aff1D}  \
    -final           NN

# ------------------------------------------------------------------------

@djunct_overlap_check \
    -ulay direct.nii.gz \
    -olay indirect_warpdeob.nii.gz \
    -prefix img_olap_dir_indir_warpdeob

@djunct_overlap_check \
    -ulay direct.nii.gz \
    -olay indirect_refitdeob.nii.gz \
    -prefix img_olap_dir_indir_refitdeob
```
... producing the image of the *indirect_refitdeob* overlaying the direct dset (these match):
![img_olap_dir_indir_refitdeob](https://user-images.githubusercontent.com/9322171/155557082-9748fe20-1d39-4f70-9ec3-524de313e09a.jpg)

... and the image of the *indirect_warpdeob* overlaying the direct dset (these do **not** match):
![img_olap_dir_indir_warpdeob](https://user-images.githubusercontent.com/9322171/155557171-7c0bc54c-2f1c-41d3-bcb2-5804bf6b82be.jpg)

**Comment by mrneont** [comment]
Most AFNI alignment programs ignore obliquity (3dAllineate, 3dQwarp), but align_epi_anat.py actually does apply it before alignment.

**Comment by mrneont** [comment]
@oesteban -

Yes, that is one way to think about it.  

This original mask has obliquity, and this is its **full** matrix (the equivalent of {q,s}form matrix) is---we see it is oblique because the 3x3 matrix part is not diagonal, it contains rotation:
```
$ cat_matvec MMM.nii.gz::IJK_TO_DICOM_REAL
       3.2031             0             0      -100.312
            0       3.19607      0.231777      -134.266
            0     -0.212116       3.49232      -30.4482
```

... and this is what it would look like 3drefit-deobliqued matrix looks like:
```
$ cat_matvec MMM.nii.gz::IJK_TO_DICOM
       3.2031             0             0      -100.312
            0        3.2031             0      -134.266
            0             0           3.5      -30.4482
```
The latter has been effectively "unrotated" in some way.

For MMM_refitdeob.nii.gz, both the IJK_TO_DICOM_REAL and IJK_TO_DICOM are the equal to each other (obliquity has been removed), and they match the latter 3drefit-deobliqued one above---
```
$ cat_matvec MMM_refitdeob.nii.gz::IJK_TO_DICOM
       3.2031             0             0      -100.312
            0        3.2031             0      -134.266
            0             0           3.5      -30.4482

$ cat_matvec MMM_refitdeob.nii.gz::IJK_TO_DICOM_REAL
       3.2031             0             0      -100.312
            0        3.2031             0      -134.266
            0             0           3.5      -30.4482
```

For MMM_warpdeob.nii.gz, both the IJK_TO_DICOM_REAL and IJK_TO_DICOM are equal to each other, but they are:
```
$ cat_matvec MMM_warpdeob.nii.gz::IJK_TO_DICOM_REAL
       3.2031             0             0      -100.312
            0        3.2031             0      -135.584
            0             0        3.2031      -45.3148

$ cat_matvec MMM_warpdeob.nii.gz::IJK_TO_DICOM_REAL
       3.2031             0             0      -100.312
            0        3.2031             0      -135.584
            0             0        3.2031      -45.3148
```

Note the difference in voxel sizes in the datasets here (read along the diagonals), because of the different evolutionary paths each traveled along (3dWarp output isotropic voxels by default; "-gridset .." could be used---but applying obliquity *could* move the dataset far in space), and using "base" in 3dAllineate instead of "master" (the latter would set the grid fully).
```
$ 3dinfo -ad3 -prefix MMM*
3.203100	3.203100	3.500000	          MMM.nii.gz
3.203100	3.203100	3.500000	MMM_refitdeob.nii.gz
3.203100	3.203100	3.203100	 MMM_warpdeob.nii.gz
```

A lot of subtle points with these grid considerations.

--pt

**Comment by oesteban** [comment]
Those `cat_matvec` calls are gold for me -- thanks much!

You had already suggested using them but didn't seem so straightforward to me at the moment. Now I regret not having tried before.

**Comment by mrneont** [comment]
Rockin', glad that's useful.

The following produces a rotation matrix:
`cat_matvec -ONELINE MMM.nii.gz::IJK_TO_DICOM_REAL MMM.nii.gz::IJK_TO_DICOM -I > mat_rot.aff12.1D `
... where mat_rot.aff12.1D  (in 3x4 form, for readability) is:
```
            1             0             0             0
            0      0.997805     0.0723602             0
            0    -0.0606045      0.997805             0
```

Applying that rotation like this to the full/oblique matrix:
```
$ cat_matvec mat_rot.aff12.1D -I MMM.nii.gz::IJK_TO_DICOM_REAL
       3.2031             0             0      -100.312
            0        3.2031    4.6044e-08      -134.266
            0   1.76702e-08           3.5      -30.4482
```
... basically produces the refit-deobliqued one IJK_TO_DICOM:
```
$ cat_matvec  MMM.nii.gz::IJK_TO_DICOM
       3.2031             0             0      -100.312
            0        3.2031             0      -134.266
            0             0           3.5      -30.4482
```

That is, that `mat_rot.aff12.1D` is the rotation (or unrotation) between them.

**Comment by oesteban** [comment]
Thanks much @mrneont - indeed I have managed to replicate `3drefit -deoblique` and ` 3dWarp -deoblique` in my settings, as well as my tests with `3dAllineate` with oblique datasets.
