### ISSUE TITLE
-combine_opts_tedana lacks spaces in resulting proc script

### ISSUE THREAD

**Issue by jbteves** [afni/afni#354]
The proc script that results from using `-m_tedana` and `-combine_opts_tedana` does not have spaces separating the option arguments if you follow, the example. For example
```
-combine_opts_tedana --tedpca kundu
```
will result in the proc script line
```
--tedpcakundu
```

**Comment by afni-rickr** [comment]
Oh my goodness!  Fixed, thanks!

**Comment by jbteves** [comment]
Would you mind pinging me when there's a new version with this patch? That way I can let people in the lab know to update.

**Comment by afni-rickr** [comment]
To be sure, do you mean a compiled package?  If so, the build takes a few hours, but expect it to be available tonight.  Anyone desparate can put db_mod.py in place.  :)

**Comment by jbteves** [comment]
Yes, that's what I meant, sorry. Does the build happen to automatically deploy to biowulf?

**Comment by afni-rickr** [comment]
Yes, I think it gets pulled around 4am, if a new version exists.
I just started a build now, it should be ready in about 3 hours (sync'ing to the server is slow), and on biowulf in the morning.

**Comment by jbteves** [comment]
Awesome, thanks @afni-rickr !
