### ISSUE TITLE
Issue in `3dttest++` when both `-permute` and `-Covariates` specified

### ISSUE THREAD

**Issue by akimbler** [afni/afni#356]
When attempting to run a 2-sample t-test using `3dttest++` with `-Clustsim` specified, while specifying both `-permute` and `-covariates` flags, the program fails with the following error 
```+ 3dttest++: AFNI version=AFNI_22.0.15 (Mar  2 2022) [64-bit]
++ Authored by: Zhark++
** AFNI converts NIFTI_datatype=256 (INT8) in file /rsfc/group/sub-group_task-rest_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz to FLOAT32
     Warnings of this type will be muted for this session.
     Set AFNI_NIFTI_TYPE_WARN to YES to see them all, NO to see none.
++ 116151 voxels in -mask dataset
++ Covariates file: 4 columns, each with 63 rows
 + Covariate column labels: subject;age;sex;mean_fd
 + Found 3 numeric columns: age sex mean_fd 
++ Number of -Clustsim threads set to 30
++ option -setA :: processing as LONG form (label label dset label dset ...)
++ have 33 volumes corresponding to option '-setA'
++ option -setB :: processing as LONG form (label label dset label dset ...)
++ have 30 volumes corresponding to option '-setB'
++ 2-sample test: '-AminusB' option is assumed
++ 2-sample test: results will be nonUser - User
++ loading covariates
[7m** ERROR:[0m -permute failure for unfathomable reasons /:(
     nx=33  ny=30  p_nxy=0  x==non-NULL  y==non-NULL
Function traceback follows:
    permute_arrays
   TT_matrix_setup
  3dttest++ main
** Command line was:
3dttest++ -prefix sub-group_task-rest_desc-2SampletTestinsulaVlh_briks -mask /rsfc/group/sub-group_task-rest_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz -Covariates /rsfc/group/insulaVlh/sub-group_task-rest_desc-1SampletTestinsulaVlh_cov.txt -Clustsim 30 -@
```
This occurs on two versions tested (22.0.15 and 20.2.06), a much older version (16.2.07) runs without error. This seems like it's potentially related to the behavior change post-March 2020 specified here 
![image](https://user-images.githubusercontent.com/21314171/157269616-81cd5935-1873-40a9-8438-322a9ab39167.png)
It may not work the way we wish, but we'd like it to be working 😅. Thanks to @JulioAPeraza for identifying this issue and providing this info.

**Comment by mrneont** [comment]
@akimbler : The rumor is that this commit:
https://github.com/afni/afni/commit/55c815d24a94938848eea0400aa70f406bf772c7
by @afni-rwcox fixes this issue, so that our next build will include it.

Thanks for pointing this out.

--pt

**Comment by akimbler** [comment]
@mrneont Thanks for the followup!

**Comment by mrneont** [comment]
Hi, @akimbler :  if it's OK, let's leave this open until we are certain that it is definitely resolved for your data...

**Comment by akimbler** [comment]
@mrneont I'll test this out as soon as I can!

**Comment by akimbler** [comment]
@mrneont Confirmed, the most recent build resolves this issue! Thanks for all your help.

**Comment by mrneont** [comment]
Fantastico!  Will now close the issue...
