### ISSUE TITLE
wishlist:  few new tags and a 'milestone'

### ISSUE THREAD

**Issue by yarikoptic** [afni/afni#38]
Would be nice to have 'testing' tag so in the future you could annotate PR 
And then it might be worth adding few Milestones:
- "cmake build"
- "comprehensive test coverage"

looking forward for some bright future when those things would happen ;)

**Comment by nno** [comment]
@afni-rickr @afni-rwcox I would be happy to add these - any objections?

**Comment by afni-rwcox** [comment]
I’ve been out of the country for a week. What’s this about?  I don’t have any principled objection to more tags.

--------------------------------------------------------------------------
|  Robert W Cox, PhD
|  Director, Scientific and Statistical Computing Core
|  NIMH & NIH  +1-301-594-9196   http://afni.nimh.nih.gov
--------------------------------------------------------------------------

**Comment by afni-rickr** [comment]
I've been here the whole time, yet am not sure what these new-fangled "testing" tags are about...   Hopefully they will not destroy the universe or send poorly-worded email to loved ones.

Is this testing tag for the purpose of having a branch that runs parallel to master (but with extra files), that is used for testing?  And are the milestones just tagged commits?

**Comment by yarikoptic** [comment]
there is a bit of collision leading to me confusing everyone.  By "tags" I meant really github "labels" as you can see them to the right of the text here and in the list of the issues.  Just that you can assign arbitrary labels to your issues or pull requests, which allows easily to filter them up

**Comment by afni-rwcox** [comment]
Since this is a government project, please keep your new labels “clean”.  Otherwise, I don’t have a problem with this idea.

--------------------------------------------------------------------------
|  Robert W Cox, PhD
|  Director, Scientific and Statistical Computing Core
|  NIMH & NIH  +1-301-594-9196   http://afni.nimh.nih.gov
--------------------------------------------------------------------------

**Comment by nno** [comment]
> Is this testing tag for the purpose of having a branch that runs parallel to master (but with extra files), that is used for testing? And are the milestones just tagged commits?

To be clear, using the github Labels and Milestone functionality is independent of the git repository itself. Thus, whether or not we would use these features, the use of git (with committing, merging, branching, etc) would remain just as it is. There would be no need (or use) for a new branch running parallel to master, and Milestones are mutually independent from using git tags (i.e. one can use neither, or only Milestones, or only git tags, or both).

The rationale for adding tags is that, when the number of issues would become larger, it would help us in filtering out particular subsets of issues. For example, in the PyMVPA project we (that includes @yarikoptic and me) use Labels such as "Confirmed Bug" and "Enhancement" (https://github.com/PyMVPA/PyMVPA/issues). 

Does that clarify the intended use of Labels and Milestone?

**Comment by afni-rickr** [comment]
Thanks @nno, that is very helpful!

**Comment by mrneont** [comment]
this appears to be closed now (i even see the "testing" tag in use?).

thanks.
