### ISSUE TITLE
3drefit truncating .nii.gz files

### ISSUE THREAD

**Issue by effigies** [afni/afni#397]
Just a heads up that a user is [reporting](https://neurostars.org/t/fmriprep-fails-during-nibabel-after-manual-realignment-to-lpi/23377/3) that running `3drefit -orient LPI bold.nii.gz` is truncating the dataset to 8192 bytes (guessing this is just the gzip block size, in this case). `gunzip`ping and then running gets the expected result.

I suspect this code assumes you can rewrite the header without rewriting the data block and a layer that makes `.nii.gz` work transparently is truncating.

**Comment by mrneont** [comment]
Hi, @effigies -

Thanks for mentioning this.  That is pretty odd;  I have not noticed this with 3drefit before, whether on a gzipped file or not.  I don't think that this is general 3drefit/gzipped NIFTI behavior.

I will ask if I can get a copy of that dataset.

**Comment by effigies** [comment]
Wow. Not at all where I guessed that would end up. Kudos for the deep dive!

**Comment by mrneont** [comment]
And, with further investigation, it is worth noting that it appears that zlib ver=1.2.9 was specifically the culprit.  From the update logs here:
https://abi-laboratory.pro/?view=timeline&l=zlib
... it might be that that specific version (and potentially ver=1.2.10, based on the timing of new version creation) might have had issues that were fixed within ver=1.2.11---after updating to that version in the dependencies, the file creation problem was not happening.

And on a final note, on our local machines, using ver=1.2.7 as a dependency was working, as well, for those keeping track of zlib version numbers to safely land on.
