### ISSUE TITLE
feat: 3dLMEr error messages mask val !=1; InputFile > 1 volume

### ISSUE THREAD

**Issue by WillForan** [afni/afni#398]
Some errors are especially hard to debug in 3dLMEr. The two most recent bites:
1) we provided a mask subset from an atlas. the masked region's value was 42 instead of 1.

> Loading required package: carData
> Error in if (ii < dimx) ii <- ii + 1 else if (jj < dimy) { : 
>   missing value where TRUE/FALSE needed
> Execution halted

2) We forgot to add subbrick selectors to the InputFile column. The message had a helpful hint, but b/c `3dinfo -same_grid` showed all to be good, we went off in the wrong direction.

> ** Error: 
>    At least one of the input files has different dimensions!
> Run "3dinfo -header_line -prefix -same_grid -n4 *.HEAD" in the directory where
> the files are stored, and pinpoint out which file(s) is the trouble maker.
> Replace *.HEAD with *.nii or something similar for other file formats.

**Comment by mrneont** [comment]
@WillForan : is it fine to close this issue now, with your PR (https://github.com/afni/afni/pull/399) having been accepted?

--pt
