### ISSUE TITLE
Mac OS 13: Can't install bootcamp R packages

### ISSUE THREAD

**Issue by wizofe** [afni/afni#417]
For an M1 Mac with Mac Os13 Ventura, I can't install the R packages required for the bootcamp, when I run

```
@afni_R_package_install -shiny -circos
```

I am getting:

```
* DONE (colourpicker)

The downloaded source packages are in
	‘/private/var/folders/w0/l_6kbqt95n32vbm4r0n4yymr0000gn/T/Rtmpu1rQ8a/downloaded_packages’
Installing: OmicCircos

Error: With R version 3.5 or greater, install Bioconductor packages using BiocManager; see https://bioconductor.org/install
Execution halted```

**Comment by pmolfese** [comment]
Hello,

What version of R do you have? 

And what's the output of `afni_system_check.py -check_all`?

**Comment by wizofe** [comment]
R Version: 4.2.2 and the output follows bellow:

```
-------------------------------- general ---------------------------------
architecture:         64bit
cpu type:             arm
system:               Darwin
release:              22.1.0
version:              Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
distribution:         13.0
number of CPUs:       10
apparent login shell: zsh
shell RC file:        .zshrc (exists)

--------------------- AFNI and related program tests ---------------------
which afni           : /Users/wizofe/abin/afni
afni version         : Precompiled binary macos_10.12_local: Nov  9 2022
                     : AFNI_22.3.05 'Lucius Verus'
AFNI_version.txt     : AFNI_22.3.05, macos_10.12_local, Nov 09 2022
which python         : /opt/homebrew/Caskroom/miniconda/base/envs/napari-env/bin/python
python version       : 3.9.13
which R              : /opt/homebrew/bin/R
R version            : R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
which tcsh           : /bin/tcsh

instances of various programs found in PATH:
    afni    : 1   (/Users/wizofe/abin/afni)
    R       : 2
      /opt/homebrew/Cellar/r/4.2.2/bin/R
      /Library/Frameworks/R.framework/Versions/3.6/Resources/bin/R
    python  : 2
      /opt/homebrew/Caskroom/miniconda/base/envs/napari-env/bin/python3.9
      /opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/bin/python3.10
    python2 : 0
    python3 : 3
      /opt/homebrew/Caskroom/miniconda/base/envs/napari-env/bin/python3.9
      /opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/bin/python3.10
      /usr/bin/python3

** have python3 but not python2

testing ability to start various programs...
    afni                 : success
    suma                 : success
    3dSkullStrip         : success
    uber_subject.py      : success
    3dAllineate          : success
    3dRSFC               : success
    SurfMesh             : success
    3dClustSim           : success
    3dMVM                : FAILURE
        Error in dyn.load(ll) :
          unable to load shared object '/Users/wizofe/abin/R_io.so':
          dlopen(/Users/wizofe/abin/R_io.so, 0x0006): tried: '/Users/wizofe/abin/R_io.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/wizofe/abin/R_io.so' (no such file), '/Users/wizofe/abin/R_io.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
        Calls: source ... withVisible -> eval -> eval -> set_R_io -> dyn.load
        Execution halted

checking for R packages...
    rPkgsInstall -pkgs ALL -check : success

R RHOME : /opt/homebrew/Cellar/r/4.2.2/lib/R

checking for $HOME files...
    .afnirc                   : found
    .sumarc                   : found
    .afni/help/all_progs.COMP : found

------------------------------ python libs -------------------------------
** failed to load module PyQt4
-- PyQt4 is no longer needed for an AFNI bootcamp

++ module loaded: matplotlib.pyplot
   module file : /opt/homebrew/Caskroom/miniconda/base/envs/napari-env/lib/python3.9/site-packages/matplotlib/pyplot.py
   matplotlib version : 3.5.2

-------------------------------- env vars --------------------------------
PATH = /opt/homebrew/Caskroom/miniconda/base/envs/napari-env/bin:/opt/homebrew/Caskroom/miniconda/base/condabin:/Users/wizofe/local/fsl/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/wizofe/Library/Application Support/JetBrains/Toolbox/scripts:/opt/homebrew/opt/python/libexec/bin:/Library/Frameworks/R.framework/Resources:/usr/local/gfortran/bin:/Users/wizofe/abin

PYTHONPATH =
R_LIBS =
LD_LIBRARY_PATH =
DYLD_LIBRARY_PATH =
DYLD_FALLBACK_LIBRARY_PATH =

------------------------------ data checks -------------------------------
data dir : missing AFNI_data6
data dir : missing AFNI_demos
data dir : missing suma_demo
data dir : missing afni_handouts
atlas    : found TT_N27+tlrc  under /Users/wizofe/abin

------------------------------ OS specific -------------------------------
XQuartz version      : 2.8.2

which brew           : /opt/homebrew/bin/brew
brew version         : Homebrew 3.6.11

-- for PyQt4 under brew, consider running:
   brew install cartr/qt4/pyqt
++ found 1 dylib files under '/opt/X11/lib/flat_namespace'
   -- found 'libXt' dylib files:
      /opt/X11/lib/flat_namespace/libXt.6.dylib
** env var DYLD_LIBRARY_PATH is not set to contain /opt/X11/lib/flat_namespace
   (so afni and suma may fail)

=========================  summary, please fix:  =========================
*  just be aware: login shell 'zsh', but our code examples use 'tcsh'
*  AFNI programs show FAILURE
*  insufficient data for AFNI bootcamp
   (see "Prepare for Bootcamp" on install pages)
*  OS X version might be old
*  consider setting DYLD_LIBRARY_PATH to /opt/X11/lib/flat_namespace
```

**Comment by afni-rickr** [comment]
Note that the 10.12 binaries are built against R 3.6 (or is it 3.5?  I forget).  To use a version as new as 4.2, you will indeed need to compile locally.  Making a current package is problematic right now, particularly due to signing issues.
We plan to make a convenience script for this, but have not yet done so, sorry.  The instructions from @pmolfese should be a good place to start.  Thanks.

**Comment by wizofe** [comment]
I am doing that now. It seems I don't have success with using AFNI through a Docker either, if you have any suggestions for that, welcome.

Thank you both!

**Comment by wizofe** [comment]
Actually following your instructions I got the following error:

```
cp: /opt/homebrew/lib/libjpeg.9.dylib: No such file or directory
```

The solution is found [here](https://stackoverflow.com/questions/42317641/pil-library-not-loaded-opt-local-lib-libjpeg-9-dylib) and is to run: `pip install --upgrade pillow`

**Comment by wizofe** [comment]
And yes, now everything works happily. Thanks for your instructions!

**Comment by wizofe** [comment]
Fixed following those instructions. ta

**Comment by wizofe** [comment]
Although #418 fixed using your instructions, after successfully compiling, I still get the same error in that one

```

```

**Comment by pmolfese** [comment]
Ah that's annoying. Ok - someone will update the install script soon-ish. In the meantime can you see if this works (first line is to launch R):

```
R
install.packages("BiocManager")
BiocManager::install("OmicCircos")
```

**Comment by pmolfese** [comment]
I believe that this is fixed by PR #419.

**Comment by timvickery** [comment]
I'm having a new issue in compiling (same issue on two macOS m2 mini's -- running 13.3.1. I'm not sure this is the best place to post but I was following @pmolfese sequence for compiling for this platform. This is a new one for me and I'm a bit lost as to how to debug it (I've successfully compiled for an M2 before). Here's the error I get: 

`/usr/bin/gcc -O2 -arch arm64 -DDARWIN -DARM_M1 -m64 -Wall -Wno-deprecated-declarations -Wcomment -Wformat -DUSE_TRACING -DHAVE_XDBE -DDONT_USE_MCW_MALLOC  -DSUMA_COMPILED  -DSUMA_GL_NO_CHECK_FRAME_BUFFER   -I. -I/opt/homebrew/include -I/opt/X11/include -I/usr/include -IGLw_local -I.. -I../niml -Igts/src  -I/opt/homebrew/include/glib-2.0  -I/opt/homebrew/lib/glib-2.0/include -I../nifti/nifti2 -I../nifti/niftilib -I../nifti/nifticdf -I../nifti/znzlib -I../3DEdge/src -I../rickr -IGLUT -I../f2c -I.. -I../niml -I../coxplot -I../ptaylor -c SUMA_IsoSurfaceFunc.c 
SUMA_IsoSurfaceFunc.c:91:14: warning: unused variable 'N_SO' [-Wunused-variable]
   int i, k, N_SO, nproc=0, n_unq, *unq=NULL;
             ^
SUMA_IsoSurfaceFunc.c:199:14: warning: variable 'n_mask' set but not used [-Wunused-but-set-variable]
   int ii=0, n_mask=0, a, b, c, d, e, f;
             ^
SUMA_IsoSurfaceFunc.c:201:17: warning: unused variable 'LocalHead' [-Wunused-variable]
   SUMA_Boolean LocalHead = NOPE;
                ^
SUMA_IsoSurfaceFunc.c:357:7: error: call to undeclared function 'compute_data'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      compute_data( *mcp , Opt->obj_type) ;
      ^
SUMA_IsoSurfaceFunc.c:370:7: error: call to undeclared function 'write1Dmcb'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      write1Dmcb(mcp);
      ^
3 warnings and 2 errors generated.
make[1]: *** [SUMA_IsoSurfaceFunc.o] Error 1
cp: SUMA/libSUMA.a: No such file or directory
cp: SUMA/libSUMA.a: No such file or directory
make: *** [libSUMA.a] Error 1
`

**Comment by afni-rickr** [comment]
Oh, this looks like my fault.  I need to propagate a new header.  I will do so and get back to you.  Thanks!

**Comment by afni-rickr** [comment]
Hi @timvickery.  Okay, I made an update for that.  Please feel free to pull and try again.  Sorry, and thanks for letting us know!

**Comment by afni-rickr** [comment]
Great, thanks!
