### ISSUE TITLE
IndexError: list index out of range with -- applying input view as +orig

### ISSUE THREAD

**Issue by winsonfzyang** [afni/afni#420]
Hello, I'm using singularity with the cmake_build to use afni. There's an error I encountered using afni_proc.py and I'm not sure why:

afni_proc.py -subj_id sub01_ses-01_run01 -blocks despike ricor tshift align                  \
>      tlrc volreg mask -tshift_opts_ts -tpattern                                               \
>      @/PHShome/wy077/adept_study/slicetiming.txt -copy_anat                                   \
>      /PHShome/wy077/adept_study/T1/anatSS.sub01.nii -anat_has_skull no                        \
>      -anat_follower anat_w_skull anat                                                         \
>      /PHShome/wy077/adept_study/T1/anatU.sub01.nii -dsets                                     \
>      /PHShome/wy077/adept_study/raw/func/ses-01/sub-ID01_ses-01_task-jhana_run-01_bold.nii.gz \
>      -ricor_regs /PHShome/wy077/adept_study/physiodata/out_1d/jhana01.1D                      \
>      -blip_reverse_dset                                                                       \
>      /PHShome/wy077/adept_study/raw/fmaps/ses-01/sub-ID01_ses-01_dir-PA_run-01_epi.nii.gz     \
>      -align_opts_aea -cost lpc+ZZ -giant_move -check_flip -tlrc_base                          \
>      MNI152_T1_2009c+tlrc -tlrc_NL_warp -tlrc_NL_warped_dsets                                 \
>      /PHShome/wy077/adept_study/T1/anatQQ.sub01.nii                                           \
>      /PHShome/wy077/adept_study/T1/anatQQ.sub01.aff12.1D                                      \
>      /PHShome/wy077/adept_study/T1/anatQQ.sub01_WARP.nii -mask_segment_anat                   \
>      yes -mask_segment_erode yes -mask_epi_anat yes -volreg_align_to                          \
>      MIN_OUTLIER -volreg_align_e2a -volreg_tlrc_warp
-- applying input view as +orig
Traceback (most recent call last):
  File "/opt/user_pip_packages/bin/afni_proc.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/opt/afni/src/src/python_scripts/scripts/afni_proc.py", line 4600, in <module>
    rv = run_proc()
  File "/opt/afni/src/src/python_scripts/scripts/afni_proc.py", line 4575, in run_proc
    rv, proc = make_proc()
  File "/opt/afni/src/src/python_scripts/scripts/afni_proc.py", line 4543, in make_proc
    if proc.create_blocks():
  File "/opt/afni/src/src/python_scripts/scripts/afni_proc.py", line 2354, in create_blocks
    rv = self.add_block(label)
  File "/opt/afni/src/src/python_scripts/scripts/afni_proc.py", line 2772, in add_block
    block = ProcessBlock(label, self)
  File "/opt/afni/src/src/python_scripts/scripts/afni_proc.py", line 4500, in __init__
    BlockModFunc[label](self, proc, proc.user_opts) # add block
  File "/opt/afni/src/src/python_scripts/afnipy/db_mod.py", line 7887, in db_mod_tlrc
    prepare_tlrc_base(proc, block)
  File "/opt/afni/src/src/python_scripts/afnipy/db_mod.py", line 7968, in prepare_tlrc_base
    if not proc.tlrc_base.locate():
  File "/opt/afni/src/src/python_scripts/afnipy/afni_base.py", line 299, in locate
    path = com.so[0]
IndexError: list index out of range

Thanks for the help!

**Comment by mrneont** [comment]
Hi-

Just as a first step, I spaced out your posted code so the options are a little easier to read:

```
afni_proc.py                                                                 \
    -subj_id               sub01_ses-01_run01                                \
    -blocks                despike ricor tshift align tlrc volreg mask       \
    -tshift_opts_ts        -tpattern  @/PHShome/wy077/adept_study/slicetiming.txt       \
    -copy_anat             /PHShome/wy077/adept_study/T1/anatSS.sub01.nii    \
    -anat_has_skull        no                                                \
    -anat_follower         anat_w_skull anat                                 \
                           /PHShome/wy077/adept_study/T1/anatU.sub01.nii     \
    -dsets                 /PHShome/wy077/adept_study/raw/func/ses-01/sub-ID01_ses-01_task-jhana_run-01_bold.nii.gz \
    -ricor_regs            /PHShome/wy077/adept_study/physiodata/out_1d/jhana01.1D \
    -blip_reverse_dset     /PHShome/wy077/adept_study/raw/fmaps/ses-01/sub-ID01_ses-01_dir-PA_run-01_epi.nii.gz \
    -align_opts_aea        -cost lpc+ZZ                                      \
                           -giant_move                                       \
                           -check_flip                                       \
    -tlrc_base             MNI152_T1_2009c+tlrc                              \
    -tlrc_NL_warp                                                            \
    -tlrc_NL_warped_dsets  /PHShome/wy077/adept_study/T1/anatQQ.sub01.nii    \
                           /PHShome/wy077/adept_study/T1/anatQQ.sub01.aff12.1D \
                           /PHShome/wy077/adept_study/T1/anatQQ.sub01_WARP.nii \
    -mask_segment_anat     yes                                               \
    -mask_segment_erode    yes                                               \
    -mask_epi_anat         yes                                               \
    -volreg_align_to       MIN_OUTLIER                                       \
    -volreg_align_e2a                                                        \
    -volreg_tlrc_warp
```

**Comment by mrneont** [comment]
It looks like an issue in the 'tlrc' block.  Maybe your template is not being found, without a path specified?

What is the output of:
`@FindAfniDsetPath MNI152_T1_2009c+tlrc`

?

**Comment by winsonfzyang** [comment]
Yes, there's an issue with the tlrc block. the `MNI152_T1_2009c+tlrc` file cant be found though. I'm using singularity with afni by installing afni with `singularity pull docker://afni/afni_cmake_build^`I checked the afni folder and indeed it doesn't have the template file. Could it be an issue with how it installed afni with singularity that not all files were installed?

**Comment by mrneont** [comment]
I see.  When we compile+distribute the binaries, we also put in a bunch of reference datasets, and label that directory as a "global" spot for AFNI to find them. That way, you don't always need to copy them around to view them in the GUI, nor do you need to use the path to them in some command line options.

To get this directory of datasets separately, you can do the following to download+unpack them somewhere on your system:
```
curl -O https://afni.nimh.nih.gov/pub/dist/atlases/afni_atlases_dist.tgz
tar -xf afni_atlases_dist.tgz
```

Then, you can refer to that full path location plus the name of the template you want in that command line call, like:
`    -tlrc_base             /SOME/PATH/TO/REF_DIRECTORY/MNI152_T1_2009c+tlrc                              \`
... or you could make that directory the value of the AFNI environment variable "AFNI_GLOBAL_SESSION", for example by putting the following line at the end of your ~/.afnirc file:
`AFNI_GLOBAL_SESSION      = /SOME/PATH/TO/REF_DIRECTORY`

In the latter case, you will know if you are successful if you open up the AFNI GUI, click "Underlay" or "Overlay" to load in a dset, and see all of the datasets in that special directory available for selection.

In the normal install situation, you should have a default file sitting in ~/.afnirc;  some people neglect that step at setup, unfortunately.  I am not sure if that will exist as part of your singularity install.  What is the output of:
```
afni_system_check.py -check_all
```
... on your system?  Is there a bottom section of "Please fix" items, giving some advice about creating a ~/.afnirc file?

**Comment by afni-rickr** [comment]
And just for reference, that error in afni_base.py was fixed just over a month ago.

**Comment by winsonfzyang** [comment]
I just downloaded the latest binaries again (might be an older version error) and the atlases. It finally worked.

Regarding the ~/.afnirc file, it is not installed when i pulled the AFNI dockerfile with singualrity. But i found the workaround by downloading the atlases. Thanks!

**Comment by afni-rickr** [comment]
That is great, thanks!

**Comment by mrneont** [comment]
That's great to know, thanks.  I will close this Issue, then, but please let us know if you have any other questions/etc. with this.
