### ISSUE TITLE
`3dmerge -gorder $binmask1 $binmask2 .. $binmaskN` output value always 1, instead of range 1 to N

### ISSUE THREAD

**Issue by WillForan** [afni/afni#439]
Apologies if I've misunderstood the intended function.

 I think `3dmerage -gorder` for 2 inputs would look like 3dcalc `minabove(0, step(a), 2*step(b))` where voxels with value in `b` but not `a` have value `2` in the output

```
3dcalc -a jRandomDataset:4,4,4,1 -b jRandomDataset:4,4,4,1 \
   -expr 'minabove(0,step(a-.5),2*step(b-.5))' \
   -prefix /tmp/calc.nii.gz -overwrite
   

3dROIstats -nobriklab -1DRformat  -nomeanout -nzvoxels -mask /tmp/calc.nii.gz{,}|column -t
name                NZcount_1  NZcount_2
/tmp/calc.nii.gz_0  12         16
```

but instead the output is all 1s

```
3dmerge -overwrite -gorder -prefix /tmp/gorder.nii.gz \
   '3dcalc(-a jRandomDataset:4,4,4,1 -expr step(a) )' \
   '3dcalc(-a jRandomDataset:4,4,4,1 -expr step(a) )' 

3dROIstats -nobriklab -1DRformat  -nomeanout -nzvoxels -mask /tmp/gorder.nii.gz{,}|column -t
name                  NZcount_1
/tmp/gorder.nii.gz_0  43
```

small sanity check: `-gcount` yields some `2`s.
```
3dmerge -overwrite -gcount -prefix /tmp/gcount.nii.gz \
   '3dcalc(-a jRandomDataset:4,4,4,1 -expr step(a) )' \
   '3dcalc(-a jRandomDataset:4,4,4,1 -expr step(a) )' 

3dROIstats -nobriklab -1DRformat  -nomeanout -nzvoxels -mask /tmp/gcount.nii.gz{,}|column -t
name                  NZcount_1  NZcount_2
/tmp/gorder.nii.gz_0  35         15

```

**Comment by afni-rickr** [comment]
Hello @WillForan.  Note that the output of -gorder will be one of the input values (or zero), not an index specifying which dataset was applied.  In your example, step(a) was used as the input, which is always 0 or 1, and so that is what the output would be.  The first example has 2*step() for the second dataset, so perhaps that is what you are looking for in the second example.  Note that -gcount gives a count at each voxel, but still not an index.

**Comment by WillForan** [comment]
ahh I see. sorry for the noise! and thanks for the quick response
I'm trying to build a single volume atlas with distinct values for each binary roi mask in a collection.  I was hoping for a way to get out of explicitly enumerating them.

**Comment by afni-rickr** [comment]
So you have (probably an alphabetical, numerically) list of masks and you want a volume with the index of the first non-zero mask (in a 1-based manner)?  Maybe something like:
  - create a single all-1 volume
  - convert to a "time series", appending the all-1 volume
   `3dTcat -prefix all_ROIs.nii.gz "mask*.nii.gz all_1.nii.gz"`
  - multiply by (t+1) to get a 1-based indexing (call the all-1 volume now an all N+1 volume)
   `3dcalc -expr 'a*(t+1)' ...`
  - change all zeros to N+1 with 3dcalc
  - find the minimum with 3dTstat
While that requires a few commands, they should be pretty straightforward.  Is that what you are picturing?

**Comment by mrneont** [comment]
Ahhh, @afni-rickr  also noted this, just before me!

**Comment by afni-rickr** [comment]
woohoo!

**Comment by WillForan** [comment]
Thanks!!
