### ISSUE TITLE
Dependencies for Debian 8

### ISSUE THREAD

**Issue by andy5995** [afni/afni#44]
I'm building on Debian 8 for the first time. I've used the suggested 'Makefile.linux_openmp_64' for a Makefile.

So far, these are the packages I've needed to install for make to continue running:

libxmu-dev
libmotif-dev (for MainW.h)
libxmhtml-dev (for libXmHTML.a)

Is there a doc that suggests other deps I may need?

**Comment by afni-rickr** [comment]
I would follow what the neurodebian group does, maybe in the neurodebian/afni repository.  No one in our group uses a Debian system.
Keep in mind that those Makefiles were created for very specific systems of ours, not for general use.  So do not expect them to simply work on your system.

**Comment by andy5995** [comment]
Acknowledged
