### ISSUE TITLE
Help RetinoProc stimulus

### ISSUE THREAD

**Issue by LucaC1997** [afni/afni#444]
Hello Afni experts
I am trying to use RetinoProc for a retinotopy analysis and I have a doubt about it. In the various scripts in the demo I see that there is no input field in which to enter the initial phase of my visual stimulus (be it the wedge for polar angles or the ring for eccentricity). Should I assume that whatever the initial phase of the stimulus is, the result is not affected, or does Afni take a default value (such as zero degrees for the wedge) as the initial phase?
Thanks in advance for your answer!!!

Luca

**Comment by afni-dglen** [comment]
I have tried to answer this on the AFNI message board here:

https://afni.nimh.nih.gov/afni/community/board/read.php?1,169276,169303#msg-169303

I'll close it here, and we can continue the conversation there if needed.
