### ISSUE TITLE
updating CircleCI testing: 

### ISSUE THREAD

**Issue by mrneont** [afni/afni#466]
Hi, @yarikoptic :

In the wake of The Great Spelling Update within the AFNI codebase, we have had to update some of the CircleCI testing.  @afni-rickr and I have been working on it, and we *thought* we had everything set., working in the pt_spell (https://github.com/afni/afni/pull/462) branch.  The test update processed appeared to be running smoothly all the way through running `datalad push`, and the testing works find on the 'safni' machine we mainly run it, as well as on Rick's personal computer.  However, we are now getting odd errors for all the tests_ptaylor through CircleCI; lots of these `FileNotFoundError` messages:
```
=========================== short test summary info ============================

FAILED scripts/test_ptaylor.py::test_3dDTtoNoisyDWI - FileNotFoundError

FAILED scripts/test_ptaylor.py::test_3ddot_beta - FileNotFoundError: [Errno 2...

FAILED scripts/test_ptaylor.py::test_3dEigsToDT - FileNotFoundError

FAILED scripts/test_ptaylor.py::test_1dDW_Grad_o_Mat_plus_plus_colmat - FileN...
```
@afni-rickr added a comment on it here, and it appears to be something with git-annex is not happy:
https://github.com/afni/afni/pull/462#issuecomment-1474253045

We are wondering if you might have a suggestion for fixing this?  We are stymied, esp. since this only seems to be a problem on CircleCI, as far as we can tell.  Any suggestions would be greatly appreciated.

**Comment by yarikoptic** [comment]
full troubleshooting with what I think went "wrong" is at https://github.com/afni/afni/pull/462#issuecomment-1474552276
