### ISSUE TITLE
Windows, Ubuntu 20.04.02 Install Errors

### ISSUE THREAD

**Issue by ramimrad** [afni/afni#477]
Hi,

I'm trying to download AFNI on my windows 10 laptop, but I've had many problems with the install process despite following the steps on the website. I first tried the quick setup steps, but I ran into many errors due to missing packages. I was able to resolve many of them, but I still have some problems I cannot resolve. I'm now doing the slow setup steps instead and during step 2 of installing prereq packages I get the errors 

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'adwaita-icon-theme-full' instead of 'gnome-icon-theme-symbolic'
Package gnome-tweak-tool is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  gnome-tweaks

E: Package 'gnome-tweak-tool' has no installation candidate
E: Unable to locate package libgfortran-8-dev
E: Unable to locate package libgfortran4

and afni_system_check.py -check_all returns 

`-------------------------------- general ---------------------------------
architecture:         64bit ELF
cpu type:             x86_64
system:               Linux
release:              4.4.0-19041-Microsoft
version:              #2311-Microsoft Tue Nov 08 17:09:00 PST 2022
distribution:         ubuntu 22.04 Jammy Jellyfish
number of CPUs:       4
apparent login shell: bash
shell RC file:        .bashrc (exists)

--------------------- AFNI and related program tests ---------------------
which afni           : /home/ramiratlmrad/abin/afni
afni version         : Precompiled binary linux_ubuntu_16_64: Apr 18 2023
                     : AFNI_23.1.01 'Publius Helvius Pertinax'
AFNI_version.txt     : AFNI_23.1.01, linux_ubuntu_16_64, Apr 18 2023
which python         : /usr/bin/python
python version       : 3.10.6
which R              : /usr/bin/R
R version            : R version 4.2.3 (2023-03-15) -- "Shortstop Beagle"
which tcsh           : /usr/bin/tcsh

instances of various programs found in PATH:
    afni    : 1   (/home/ramiratlmrad/abin/afni)
    R       : 1   (/usr/bin/R)
    python  : 1   (/usr/bin/python3.10)
    python2 : 0
    python3 : 1   (/usr/bin/python3.10)

** have python3 but not python2

testing ability to start various programs...
    afni                 : success
    suma                 : success
    3dSkullStrip         : FAILURE
        3dSkullStrip: error while loading shared libraries: libgsl.so.19: cannot open shared object file: No such file or directory
    uber_subject.py      : success
    3dAllineate          : success
    3dRSFC               : FAILURE
        3dRSFC: error while loading shared libraries: libgsl.so.19: cannot open shared object file: No such file or directory
    SurfMesh             : success
    3dClustSim           : success
    3dMVM                : success

checking for R packages...
    rPkgsInstall -pkgs ALL -check : success

R RHOME : /usr/lib/R

checking for $HOME files...
    .afnirc                   : found
    .sumarc                   : found
    .afni/help/all_progs.COMP : found

------------------------------ python libs -------------------------------
** failed to load module PyQt4
-- PyQt4 is no longer needed for an AFNI bootcamp

++ module loaded: matplotlib.pyplot
   module file : /home/ramiratlmrad/.local/lib/python3.10/site-packages/matplotlib/pyplot.py
   matplotlib version : 3.7.1

-------------------------------- env vars --------------------------------
PATH = /home/ramiratlmrad/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.Ubuntu22.04LTS_2204.2.43.0_x64__79rhkp1fndgsc:/mnt/c/Program Files/Eclipse Adoptium/jdk-17.0.1.12-hotspot/bin:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/ProgramData/Oracle/Java/javapath:/mnt/c/Program Files (x86)/Razer Chroma SDK/bin:/mnt/c/Program Files/Razer Chroma SDK/bin:/mnt/c/Program Files (x86)/Intel/iCLS Client/:/mnt/c/Program Files/Intel/iCLS Client/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/WiFi/bin/:/mnt/c/Program Files/Common Files/Intel/WirelessCommon/:/mnt/c/Program Files (x86)/Windows Live/Shared:/mnt/c/WINDOWS/system32/config/systemprofile/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/Intel/WiFi/bin/:/mnt/c/Program Files/Common Files/Intel/WirelessCommon/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Users/Hussam/AppData/Local/Programs/Python/Python37-32/Scripts/:/mnt/c/Users/Hussam/AppData/Local/Programs/Python/Python37-32/:/mnt/c/Users/Hussam/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Hussam/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/nrn/bin:/mnt/c/nrn/mingw/usr/bin:/snap/bin:/home/ramiratlmrad/abin

PYTHONPATH =
R_LIBS = /home/ramiratlmrad/R

LD_LIBRARY_PATH =
DYLD_LIBRARY_PATH =
DYLD_FALLBACK_LIBRARY_PATH =

----------------------------- eval dot files -----------------------------

   -- good: .tcshrc seems to contain 'source .cshrc'
   -- considered operations: path, flatdir, apsearch
      (not on a mac, should skip flatdir)

   -- note: followers should not need edits, so edit flags should be 0
      (have 1 follower(s), which can be ignored)

   dot file test : want 1 modifications across 3 files:

      file             path  flatdir  apsearch        follower
      ---------------  ----  -------  --------        --------
      .cshrc           0     0        1               0
      .tcshrc          0     0        0               1
      .bashrc          0     0        0               0

------------------------------ data checks -------------------------------
data dir : found AFNI_data6   under $HOME (226714M Avail)
           top history: ...Nov 2022 [rickr]: s05: added align_unifize_epi local
data dir : found AFNI_demos   under $HOME
           top history: ...ct 2020 [taylorp]: updated scripts under FATCAT_DEMO
data dir : found suma_demo    under $HOME
           top history: ...s_New/data/Build_tmp on Mon Mar  4 11:56:45 EST 2013
data dir : found afni_handouts under $HOME
atlas    : found TT_N27+tlrc  under /home/ramiratlmrad/abin

------------------------------ OS specific -------------------------------
which apt-get        : /usr/bin/apt-get
apt-get version      : apt 2.4.9 (amd64)

have Ubuntu system: ubuntu 22.04 Jammy Jellyfish
have Ubuntu afni  : Precompiled binary linux_ubuntu_16_64: Apr 18 2023

=========================  summary, please fix:  =========================
*  just be aware: login shell 'bash', but our code examples use 'tcsh'
*  AFNI programs show FAILURE
*  dot file test : want 1 modifications across 3 files:`

Any help would be greatly appreciated!

**Comment by afni-rickr** [comment]
Hello,

Note that you seem to be running Ubuntu 22.04, not 20.04.  So maybe you are not following the correct instruction page.  

For example, your installed gsl version is 27.  For gnome-tweak-tool, install package gnome-tweaks (not the tool itself), and the fortran version is 11.

To fix those issues, consider running the commands:

`sudo ln -s /usr/lib/x86_64-linux-gnu/libgsl.so.27 /usr/lib/x86_64-linux-gnu/libgsl.so.19`
`sudo apt-get install -y gnome-tweaks libgfortran-11-dev`

Hope that helps!

**Comment by ramimrad** [comment]
Hi,

Thanks for the quick response. I thought I was on 20.04, so you are correct in pointing out that I am on the wrong installation page. I believe everything is fine now, but the check returns

-------------------------------- general ---------------------------------
architecture:         64bit ELF
cpu type:             x86_64
system:               Linux
release:              4.4.0-19041-Microsoft
version:              #2311-Microsoft Tue Nov 08 17:09:00 PST 2022
distribution:         ubuntu 22.04 Jammy Jellyfish
number of CPUs:       4
apparent login shell: bash
shell RC file:        .bashrc (exists)

--------------------- AFNI and related program tests ---------------------
which afni           : /home/ramiratlmrad/abin/afni
afni version         : Precompiled binary linux_ubuntu_16_64: Apr 18 2023
                     : AFNI_23.1.01 'Publius Helvius Pertinax'
AFNI_version.txt     : AFNI_23.1.01, linux_ubuntu_16_64, Apr 18 2023
which python         : /usr/bin/python
python version       : 3.10.6
which R              : /usr/bin/R
R version            : R version 4.2.3 (2023-03-15) -- "Shortstop Beagle"
which tcsh           : /usr/bin/tcsh

instances of various programs found in PATH:
    afni    : 1   (/home/ramiratlmrad/abin/afni)
    R       : 1   (/usr/bin/R)
    python  : 1   (/usr/bin/python3.10)
    python2 : 0
    python3 : 1   (/usr/bin/python3.10)

** have python3 but not python2

testing ability to start various programs...
    afni                 : success
    suma                 : success
    3dSkullStrip         : success
    uber_subject.py      : success
    3dAllineate          : success
    3dRSFC               : success
    SurfMesh             : success
    3dClustSim           : success
    3dMVM                : success

checking for R packages...
    rPkgsInstall -pkgs ALL -check : success

R RHOME : /usr/lib/R

checking for $HOME files...
    .afnirc                   : found
    .sumarc                   : found
    .afni/help/all_progs.COMP : found

------------------------------ python libs -------------------------------
** failed to load module PyQt4
-- PyQt4 is no longer needed for an AFNI bootcamp

++ module loaded: matplotlib.pyplot
   module file : /home/ramiratlmrad/.local/lib/python3.10/site-packages/matplotlib/pyplot.py
   matplotlib version : 3.7.1

-------------------------------- env vars --------------------------------
PATH = /home/ramiratlmrad/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.Ubuntu22.04LTS_2204.2.43.0_x64__79rhkp1fndgsc:/mnt/c/Program Files/Eclipse Adoptium/jdk-17.0.1.12-hotspot/bin:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/ProgramData/Oracle/Java/javapath:/mnt/c/Program Files (x86)/Razer Chroma SDK/bin:/mnt/c/Program Files/Razer Chroma SDK/bin:/mnt/c/Program Files (x86)/Intel/iCLS Client/:/mnt/c/Program Files/Intel/iCLS Client/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/WiFi/bin/:/mnt/c/Program Files/Common Files/Intel/WirelessCommon/:/mnt/c/Program Files (x86)/Windows Live/Shared:/mnt/c/WINDOWS/system32/config/systemprofile/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/Intel/WiFi/bin/:/mnt/c/Program Files/Common Files/Intel/WirelessCommon/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Users/Hussam/AppData/Local/Programs/Python/Python37-32/Scripts/:/mnt/c/Users/Hussam/AppData/Local/Programs/Python/Python37-32/:/mnt/c/Users/Hussam/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Hussam/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/nrn/bin:/mnt/c/nrn/mingw/usr/bin:/snap/bin:/home/ramiratlmrad/abin

PYTHONPATH =
R_LIBS = /home/ramiratlmrad/R

LD_LIBRARY_PATH =
DYLD_LIBRARY_PATH =
DYLD_FALLBACK_LIBRARY_PATH =

----------------------------- eval dot files -----------------------------

   -- good: .tcshrc seems to contain 'source .cshrc'
   -- considered operations: path, flatdir, apsearch
      (not on a mac, should skip flatdir)

   -- note: followers should not need edits, so edit flags should be 0
      (have 1 follower(s), which can be ignored)

   dot file test : want 1 modifications across 3 files:

      file             path  flatdir  apsearch        follower
      ---------------  ----  -------  --------        --------
      .cshrc           0     0        1               0
      .tcshrc          0     0        0               1
      .bashrc          0     0        0               0

------------------------------ data checks -------------------------------
data dir : found AFNI_data6   under $HOME (226714M Avail)
           top history: ...Nov 2022 [rickr]: s05: added align_unifize_epi local
data dir : found AFNI_demos   under $HOME
           top history: ...ct 2020 [taylorp]: updated scripts under FATCAT_DEMO
data dir : found suma_demo    under $HOME
           top history: ...s_New/data/Build_tmp on Mon Mar  4 11:56:45 EST 2013
data dir : found afni_handouts under $HOME
atlas    : found TT_N27+tlrc  under /home/ramiratlmrad/abin

------------------------------ OS specific -------------------------------
which apt-get        : /usr/bin/apt-get
apt-get version      : apt 2.4.9 (amd64)

have Ubuntu system: ubuntu 22.04 Jammy Jellyfish
have Ubuntu afni  : Precompiled binary linux_ubuntu_16_64: Apr 18 2023

=========================  summary, please fix:  =========================
*  just be aware: login shell 'bash', but our code examples use 'tcsh'
*  dot file test : want 1 modifications across 3 files:

Does the "want 1 modifications" prompt matter?

**Comment by afni-rickr** [comment]
It does not matter too much.  The modification would be to:
`source ~/.afni/help/all_progs.COMP` in your .cshrc file.
That gives tab completion for options to AFNI programs.
However, it does not matter, since bash is your login shell.  I should probably remove that as an update warning in such a case.

**Comment by ramimrad** [comment]
Great, thanks for the help!
