### ISSUE TITLE
AFNI not awesome enough

### ISSUE THREAD

**Issue by aclark4life** [afni/afni#5]
Please make AFNI more awesome ASAP, thanks

**Comment by ischwabacher** [comment]
Today AFNI was awesome enough for my needs:
```
Error in if (dd[3] == 77001) ee[2] = ee[2]/1000 : 
  argument is of length zero
Calls: dset.attr
```
This would have been so much harder to debug if that enum were `{0, 1, 2}`...

**Comment by nno** [comment]
@aclark4life, could you please elaborate why you think that AFNI is not awesome enough? Do you have concrete suggestions or ideas about how you think it can be made more awesome?

(I'm assuming good faith here, and that you are not a troll)

**Comment by afni-rickr** [comment]
Try adding the -please_do_more_awesome_stuff option.  The default is still -do_not_be_so_awesome_as_to_make_researchers_dispensable, though that is obviously for backward compatibility.

**Comment by aclark4life** [comment]
Thanks all :cake:. I ran AFNI with the -please_do_more_awesome_stuff option and it became more awesome as expected. It also mowed and weed whacked my lawn for extra awesomeness! Closing this but please reopen if AFNI is ever not awesome enough again.
