### ISSUE TITLE
Problem with the website (Forbidden) 

### ISSUE THREAD

**Issue by essheh** [afni/afni#501]
Hi, 

I've been trying to install AFNI, but currently the website appears to be broken. When I try to acces most of the website I get a blank webpage where Forbidenn is written in bold with the error : "You don't have permission to access /pub/dist/doc/htmldoc/background_install/main_toc.html on this server." At last, this problems prevents me from downloading the files required to install AFNI.  

I'm not quite sure this is the right place to write this, because it's not concerning the code itself, but I've tried many things. For instance the "contact us" section of the website, but I can't send a message because the captcha apperas to be broken. Also, I can't acces the message board either (it appears to be loading, but It doesn't ultimately loads).   

Thank you,

François

**Comment by mrneont** [comment]
Hi, François-

We have a server issue at the moment, unfortunately, which we are trying to resolve.  Hopefully we will be back up and running soon.

It is certainly fine to write here.

The Message Board is on a separate server---at least the new one---and appears unscathed.  Are you trying here:
https://discuss.afni.nimh.nih.gov/
?  Please let me know if that doesn't work for reading/posting.

--pt

**Comment by mrneont** [comment]
Howdy-

And the docs should be back up now.

What OS are you building on?

--pt

**Comment by essheh** [comment]
Hi,

Everything seems to be working correctly, including the Message Board which I don't know why I wasn't able to load earlier.

Also, I'll be building AFNI on Ubuntu 20.04. 

Thanks for the quick feedback! 

François

**Comment by mrneont** [comment]
OK, cool, glad to hear it, and thanks for checking about this.

--pt
