### ISSUE TITLE
R_LIBS forced set by @update.afni.binaries

### ISSUE THREAD

**Issue by neurorepro** [afni/afni#510]
It looks like @update.afni.binaries does not take into account existing R library paths and "forces set" the R_LIBS environment variable in `.bashrc` (last line in code snippet below):
```bash
# auto-inserted by @update.afni.binaries :
export PATH=${PATH}:/path/to/afni/abin
export R_LIBS=${HOME}/R
```

The problem is that it overrides any preset of R library. For example in my case I set `R_LIBS_USER` in `.Renviron` file to indicate where the R libraries should go and I needed time to figure out why there would not go as per the R configuration set properly.

Is it intended behavior to have this explicitly set ? Isn't it an issue that it overrides pre-configured R library path as in this case ?

**Comment by afni-rickr** [comment]
Hello @neurorepro.  For reference, I do not think it was @update.afni.binaries that put the R_LIBS line in there, though we do tend to suggest it.  And for the variable updates that it does (e.g., $PATH), the user requests them.

**Comment by neurorepro** [comment]
Hi @afni-rickr , there is a comment line just before saying `# auto-inserted by @update.afni.binaries` so i was thinking it may be auto inserted by `@update.afni.binaries` :)

**Comment by afni-rickr** [comment]
Yes.  Because of that it took me some serious digging to be sure it wasn't from @uab, including historically.  :)   Thanks.
