### ISSUE TITLE
Failure to set the key cen_lim_mot_yax

### ISSUE THREAD

**Issue by neurolabusc** [afni/afni#512]
This extends the recent patch to [lib_apqc_tcsh.py](https://github.com/afni/afni/commit/40a918c98c5ae14b6e3bc018f40beed6cc8bc764#diff-4825689d17c01d042ff677a6a733dd69798bfa173c9915d9009f572f60ca4bd9). Running the classic tutorial script [s01.ap.simple](https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/unix_tutorial/misc/install.data.html) fails on MacOS computers with recent builds of AFNI:

```
$ tcsh -xef proc.FT 2>&1 | tee output.proc.FT
++ APQC create: qc_08_vstat_V-A_GLT_0_Coef
++ APQC create: qc_09_mot_enorm
Traceback (most recent call last):
  File "/Users/chris/abin/apqc_make_tcsh.py", line 709, in <module>
    cmd      = lat.apqc_mot_enorm( ap_ssdict, obase, "mot", "enorm", 
  File "/Users/chris/abin/afnipy/lib_apqc_tcsh.py", line 1604, in apqc_mot_enorm
    cmd = '''
KeyError: 'cen_lim_mot_yax'
``` 
I fixed this by insert a line into  [lib_apqc_tcsh.py](https://github.com/afni/afni/blob/61f49f1c4609484c499906611aecf305daca1fe0/src/python_scripts/afnipy/lib_apqc_tcsh.py#L1104)

```
ap_ssdict['cen_lim_all_yax'] = ''
```

**Comment by mrneont** [comment]
Hi, @neurolabusc : great, thanks.  Sorry I missed that out in the updates.  I will hopefully be able to test this soon here.

--pt

**Comment by mrneont** [comment]
Hi, @neurolabusc : OK, I have looked at this and seen how I should have initialized some of these 1dplot/1dplot.py params earlier, to address cases of not-including censoring for *both* pythonic- and basic-mode cases.  This should be addressed now more thoroughly in this commit:
https://github.com/afni/afni/commit/5660b2147d69e2c1b4eecf46df03e8bdb7404932

Sorry to not have fixed these more generally when you first pointed out the issue.  Please let me know if anything goes amiss, using these updates.

--pt

**Comment by mrneont** [comment]
Hi, @neurolabusc : How is this issue looking on your side?  Is this closeable?

thanks,
pt

**Comment by neurolabusc** [comment]
@mrneont yes the bug is fixed, so I am closing.

As an aside, when I tested on Python 3.11.4 the script [afni_proc.py](https://github.com/afni/afni/blob/2d03b4de70b83ef4e6277dda9813b4fd235fca1f/src/python_scripts/scripts/afni_proc.py#L3520) would explicitly write the `echo` command as well as the output for the echo command to the terminal: 


```
echo \nconsider running: \n

consider running: 

echo    afni_open -b FT.results/QC_FT/index.html
   afni_open -b FT.results/QC_FT/index.html
echo 

endif
cd ..
echo execution finished: `date`
date
execution finished: Thu Sep 14 08:47:10 AM EDT 2023
```

**Comment by mrneont** [comment]
Hi, @neurolabusc : Great, glad the bug has been successfully squashed.

Re. the echos at the end of the afni_proc.py script:  I believe that is a Mac-specific thing.  It takes the \n characters literally, instead of as newline characters.  On Linux, the correct interpretation as newlines occurs.  I have never been sure of why Macs have that happen.

**Comment by neurolabusc** [comment]
@mrneont this is not MacOS specific. I observed this on a x86 Linux kernel 6.2 with Python 3.11.4.

**Comment by mrneont** [comment]
Oh, and continuing this "closed" issue discussion... I think it is because the `proc.*` script has "-xef" in the shebang, and the "-x" there means that each command is literally reported before executing.  I guess the way out of that dual echo would be to have apqc_make_html.py itself output the "consider running:" message.  Will ponder that, thanks.
