### ISSUE TITLE
macOS ARM rsync path

### ISSUE THREAD

**Issue by spartaaa-git** [afni/afni#518]
The source path for ARM differs from that of Intel, per this document:
    https://github.com/afni/afni/blob/master/src/other_builds/OS_notes.macos_12_x86_64_b_user.txt

Instructions say:
    # we already have atlases, and don't need ~/afni_build/afni_atlases_dist
    rsync -av $HOME/afni_build/build_src/macos_12_x86_64/ ~/abin/
    # --- OR, for ARM:
    rsync -av $HOME/afni_build/build_src/macos_13_ARM_clang/ ~/abin/

They should be:
    # we already have atlases, and don't need ~/afni_build/afni_atlases_dist
    rsync -av $HOME/afni_build/build_src/macos_12_x86_64/ ~/abin/
    # --- OR, for ARM:
    rsync -av $HOME/afni_build/build/build_src/macos_13_ARM_clang/ ~/abin/

**Comment by spartaaa-git** [comment]
Rather this is the issue:

build_afni.py -build_root $HOME/afni_build -package macos_12_x86_64
  # --- OR, for ARM:
build_afni.py -build_root $HOME/afni/build -package macos_13_ARM_clang

where it should be:

build_afni.py -build_root $HOME/afni_build -package macos_12_x86_64
  # --- OR, for ARM:
build_afni.py -build_root $HOME/afni_build -package macos_13_ARM_clang

This would create uniformity across both chip architectures.

**Comment by afni-rickr** [comment]
Oh, indeed, that / should be a _.  Thanks for pointing it out!
