### ISSUE TITLE
Potential BUG in @djunct_montage_coordinator: master

### ISSUE THREAD

**Issue by toomanycats** [afni/afni#520]
Fresh install via `git clone/master`, building on `CentOS 7` using `Makefile.linux_centos_7_64`.

I've installed the system dependencies and created a Python3 environment with `matplotlib` and `numpy`.

The build works fine ( except it doesn't stop when a dep is missing ). However, when attempting to use this program I get an odd error:

    chauffeur_afni                     \
            -ulay    MOT-LA-001-1a37.pepolar_pa.nii.gz      \
            -prefix  PRETTY_PICTURE         \
            -montx 5 -monty 3               \
            -set_xhairs OFF                 \
            -label_mode 1 -label_size 4     \
            -do_clean
    ++ My command:
    @chauffeur_afni -ulay MOT-LA-001-1a37.pepolar_pa.nii.gz -prefix PRETTY_PICTURE -montx 5 -monty 3 -set_xhairs OFF -label_mode 1 -label_size 4 -do_clean

    ++ Using AFNI ver : AFNI_23.2.08
    ++ chauffeur ver  : 6.61

    ------------------ start of optionizing ------------------

    ++ Found input file:   MOT-LA-001-1a37.pepolar_pa.nii.gz
    +* Noting: you did NOT provide an overlay, and yet
            you did NOT turn off the overlay with '-olay_off'
        --> so I assume you just want to view the underlay.
    ++ Using blowup factor: 2
    ++ Using opacity:  6
    ++ Making temporary work directory to copy vis files: ./__tmp_chauf_u59Dz40OAWi
    ++ Converted 0 to labels
    ++ Final subbrick indices: -1 -1 -1
    ++ Copy ulay to visualize (volumetric) within user's range:
    *+ WARNING:   If you are performing spatial transformations on an oblique dset,
    such as /m/Dev/Dev_asl_mot/Raw/MOT-LA-001-1/MOT-LA-001-1a37.pepolar_pa.nii.gz,
    or viewing/combining it with volumes of differing obliquity,
    you should consider running:
        3dWarp -deoblique
    on this and  other oblique datasets in the same session.
    See 3dWarp -help for details.
    ++ Oblique dataset:/m/Dev/Dev_asl_mot/Raw/MOT-LA-001-1/MOT-LA-001-1a37.pepolar_pa.nii.gz is 3.899329 degrees from plumb.
    *+ WARNING:   If you are performing spatial transformations on an oblique dset,
    such as /m/Dev/Dev_asl_mot/Raw/MOT-LA-001-1/MOT-LA-001-1a37.pepolar_pa.nii.gz,
    or viewing/combining it with volumes of differing obliquity,
    you should consider running:
        3dWarp -deoblique
    on this and  other oblique datasets in the same session.
    See 3dWarp -help for details.
    ++ Oblique dataset:/m/Dev/Dev_asl_mot/Raw/MOT-LA-001-1/MOT-LA-001-1a37.pepolar_pa.nii.gz is 3.899329 degrees from plumb.
    ++ Ulay to be visualized within user range:
    [0%, 98%] -> [0.000000, 17211.000000]
    ++ 3dcalc: AFNI version=AFNI_23.2.08 (Sep  7 2023) [64-bit]
    ++ Authored by: A cast of thousands
    no valid niml files found to define atlases and spaces
    ++ Output dataset ././__tmp_chauf_u59Dz40OAWi/tmp_ulay.nii
    ++ No overlay viewing
    ++ Dimensions (xyzt): 86 86 60 1
    ++ (initial) Slice spacing ordered (x,y,z) is:  5 5 4
    ++ 3dmaskdump: AFNI version=AFNI_23.2.08 (Sep  7 2023) [64-bit]
    ** FATAL ERROR: Can't open dataset 3dcalc!

Unfortunately, the script doesn't catch the error and it continues and doesn't kill the child process running `Xvbf`.
Does `tcsh` not have `traps` ?

I've traced what I think the  bad call is to here:  `@djunct_montage_coordinator` 

    sed -n '214,217p' src/scripts_install/@djunct_montage_coordinator

    # has RGB type, which would make 3dmaskdump whine (and the value
    # doesn't matter here---we just want ijk->xyz conversion for coords).
    set mdumpout = `3dmaskdump -ibox $coors -noijk -xyz \
                "3dcalc -a ${ulay}[0] -expr a -byte"`

I think the idea is to take the output of a subshell call but I don't think that works as written. Unless `3dmaskdump` has some interesting input options.

I tested like this:

    3dmaskdump "3dcalc -a MOT-LA-001-1a37.pepolar_pa.nii.gz -expr a -byte"
    ** FATAL ERROR: Can't open dataset 3dcalc!

Same error as before.

**UPDATE**

After RTFM more, I found this option:

      -cmask 'opts' Means to execute the options enclosed in single
                  quotes as a 3dcalc-like program, and produce
                  produce a mask from the resulting 3D brick.
 
I don't see how the code could work as-is. Single quotes will not allow shell expansion afaik (not a csh user).
What seems to work is this:

    3dcalc -a ${ulay} -expr a -byte
    set mdumpout = `3dmaskdump -ibox $coors -noijk -xyz calc+orig`

**Comment by mrneont** [comment]
Hm, that's odd.  It works for me on Ubuntu and Macs (just tested it now, same command with FT_anat+orig.HEAD from the Bootcamp data), and I haven't seen this pathological error come up before.  

To me, the syntax of that 3dcalc expression seems fine;  it uses double quotes to be able to expand variables.

What is the output of this for your dset?
```
3dinfo -n4 -datum MOT-LA-001-1a37.pepolar_pa.nii.gz 
```

Also, could you please run your `@chauffeur_afni` command again, adding the "-echo" option for more verbose output, and send me the output?  It might be obnoxiously long here, so you can email it to me, perhaps (I will send you a message).

--pt

**Comment by mrneont** [comment]
Oh, I guess I can't send a personal message on github. Well, hopefully you can find my email, I guess.

**Comment by toomanycats** [comment]
I found the parent source of the issue. In order to keep and use multiple versions of software, my group has been 
creating a shell wrapper system. Thus `3dcalc` was not being called directly, but being passed. That seems to have broken more complex argument handling.

For now I'm going to make the newest version our default and not use this versioning system.

**Comment by mrneont** [comment]
Wow, that is a pretty subtle thing to track down---thanks for doing so, and for letting us know.  

Hope that underlying changeover makes everything simpler for processing.
