### ISSUE TITLE
Unable to Install R Packages as Root

### ISSUE THREAD

**Issue by toomanycats** [afni/afni#522]
My group keeps our binaries in a read only filesystem. In order to install some missing R packages, I
mount the location of AFNI as 'rw' which allows an admin using `sudo` to make changes.

My `afni` is installed in `/opt/afni`.

The `tcsh` script hides the full error so I called it like so from `/opt/afnin/abin`. I've truncated the output a bit.

     sudo R --file=./rPkgsInstall.R --args -pkgs corrplot

    R version 3.6.0 (2019-04-26) -- "Planting of a Tree"

    > #!/usr/bin/env AFNI_Batch_R
    >
    > #Clean up
    > rm(list = ls())
    >
    > first.in.path <- function(file) {
    +    ff <- paste(strsplit(Sys.getenv('PATH'),':')[[1]],'/', file, sep='')
    +    ff<-ff[lapply(ff,file.exists)==TRUE];
    +    cat('Using ', ff[1],'\n');
    +    return(gsub('//','/',ff[1], fixed=TRUE))
    + }
    > source(first.in.path('AFNIio.R'))
    Using  NA
    Error in if (file == "") { : missing value where TRUE/FALSE needed
    Calls: source
    Execution halted

I find that syntax hard to understand. I think it's trying to  pick off the first entry in PATH and concatenate it with something...
That `AFNIio.R` is all over the place but I don't know what it means.

**Comment by toomanycats** [comment]
I've made some progress using the official method. It would appear that the `R` version needs to be `4.0.0+`.
In addition, the `gcc` needs to be `6+` to access `c++17` which some `R` packages complained about.

For CentOS 7, that means using the the `SCL` [scl pages](https://github.com/sclorg/centos-release-scl)
    
    scl enable devtoolset-7 bash

Along with becoming `root` and setting some custom environment variables pertinent to our system configuration.

**Comment by afni-rickr** [comment]
@toomanycats Thanks a lot for following up with the details!

**Comment by toomanycats** [comment]
Turns out it took more effort. There's also a dependency on `cmake` version greather than `3.2`. Just put it on your `PATH` and it will be found by the `R` compiler.

Also, it's not enough to set the `devtool` environment to pickup `gcc-7`. You also have to edit the R cmake file:
lib64/R/etc/Makeconf

    CXX17 = /opt/rh/devtoolset-7/root/usr/bin/gcc
    CXX17FLAGS =  $(LTO)
    CXX17PICFLAGS = -fPIC
    CXX17STD =  -std=gnu++17
