### ISSUE TITLE
how to avoid Error: XtCreateWidget "glxarea" requires non-NULL widget class

### ISSUE THREAD

**Issue by yarikoptic** [afni/afni#53]
this is pretty much unrelated to your build, although I think I replicate it if I use other_builds/Makefile.linux_ubuntu_12_64 instead of other_builds/Makefile.linux_openmp_64_trusty on my Debian stretch/sid box.

```
1056	   if (!SUMA_X_SurfaceViewer_Create ()) {
(gdb) s
Error: XtCreateWidget "glxarea" requires non-NULL widget class
[Inferior 1 (process 32571) exited with code 01]
```

do you know what particular change in the build instructions "resolves" this issue... (I have an idea but so far knowing that didn't help ;))

thanks in advance for the hints

**Comment by yarikoptic** [comment]
any clues @afni-rickr ? ;-)

**Comment by crcox** [comment]
Is there any movement on this issue? I'm running:

afni --version
Precompiled binary Debian-x86_64-1-gnu: Jun 12 2017 (Version Debian-16.2.07~dfsg.1-5~nd16.04+1)

And I get this error any time I try to start SUMA.

I'm running on Ubuntu 16.04 in Virtual Box.

**Comment by afni-rickr** [comment]
It looks like this is due to the declaration of glwDrawingAreaWidgetClass in GLwDrawA.h, which comes with the mesa-libGLw-devel package.  That header has the line:
GLAPI WidgetClass glwDrawingAreaWidgetClass;
And particularly with dynamic linking, and possibly based on the compiler, if the actual object (glwDrawingAreaWidgetClass) is not found elsewhere, it is assumed to be a definition (since no extern).  But then that new variable is NULL.

This has been working well declaring that variable (there are 2 GLAPI WidgetClass variables there) as extern:
extern GLAPI WidgetClass glwDrawingAreaWidgetClass;

Here is a discussion: http://marc.info/?l=cygwin-xfree&m=141268983004514&w=2

Again, using extern, suma has been running well.

**Comment by afni-rickr** [comment]
Also, if you really want suma, consider trying the Ubuntu 16 version
here: https://afni.nimh.nih.gov/pub/dist/bin/linux_ubuntu_16_64/suma .
That is compiled with the 'extern' change, and could hopefully be used
for now, maybe giving it a slightly different name.

**Comment by crcox** [comment]
Using the suma executable from https://afni.nimh.nih.gov/pub/dist/bin/linux_ubuntu_16_64/suma solved my problem! Thanks.

**Comment by yarikoptic** [comment]
Afaik Issue  was  resolved. Was your system up to date?

**Comment by crcox** [comment]
Here is my version information. Before writing in, I did `apt-get update && apt-get upgrade afni` and the problem persisted, so I think I am up to date (unless there is a separate upgrade call for suma).
```
afni --version                       
Precompiled binary Debian-x86_64-1-gnu: Jun 12 2017 (Version Debian-16.2.07~dfsg.1-5~nd16.04+1)
suma -version 

Compile Date:
   Jun 12 2017
```

**Comment by afni-rickr** [comment]
That is good news, @yarikoptic, is 'extern' going to move upstream?

**Comment by mrneont** [comment]
This issue appears to have been resolved (a while back).  Closing now...

**Comment by leej3** [comment]
Just for posterity, the fixing change was never upstreamed.

Specifcally the glw library (usually called something like mesalib-glw) [had an extern removed](https://gitlab.freedesktop.org/mesa/glw/-/commit/9a10f52f031045150c6e1d3a1e7a7266d530333b) from one of the headers that AFNI's version [still has](https://github.com/afni/afni/blob/185abb051646fd2efc532d087485a7656c6067f5/src/SUMA/GLw_local/GL/GLwDrawA.h#L147). So AFNI builds fine with the version supplied by neurodebian but the version on debian stable and homebrew's will still cause the this runtime error.

Some possible fixes for people who encounter this error are:
+ Follow the instructions to modify the [system header](https://github.com/afni/afni/blob/af21f2566374a7358889bac52798b73ec5fb1c7d/src/other_builds/OS_notes.linux_ubuntu_16_64#L15),
+ Build using the version in AFNI's repo using something like [this](https://github.com/afni/afni/blob/af21f2566374a7358889bac52798b73ec5fb1c7d/src/other_builds/Makefile.linux_ubuntu_16_64_glw_local_shared#L54)
+ Use the cmake build infrastructure that [checks](https://github.com/afni/afni/blob/af21f2566374a7358889bac52798b73ec5fb1c7d/cmake/FindGLw.cmake#L72) if the version of GLW that is going to be used for the build has a version that will work for the AFNI gui.

**Comment by afni-rickr** [comment]
I just realized now that this *has* been upstreamed, at least in Fedora.  The jump from Fedora 30 to 31 shows a change in GLwDrawA.h to include the extern for the case of __GNUC__ >= 4.  And Fedora 31 (with the fix) came out in Oct, 2019.

**Comment by afni-rickr** [comment]
@yarikoptic Can you verify whether this is fixed in current Debian?  Please feel free to mail me `/usr/include/GL/GLwDrawA.h`.  Thanks!

**Comment by yarikoptic** [comment]
This is a file I have http://www.onerussian.com/tmp/GLwDrawA.h  on my laptop from 
```shell
$> apt-cache policy libglw1-mesa-dev
libglw1-mesa-dev:
  Installed: 8.0.0-1.1+b1
  Candidate: 8.0.0-1.1+b1
  Version table:
 *** 8.0.0-1.1+b1 900
        100 http://deb.debian.org/debian buster/main amd64 Packages
        900 http://deb.debian.org/debian bullseye/main amd64 Packages
        600 http://http.debian.net/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by afni-rickr** [comment]
Too bad, the extern is not in that.  Fedora 31 has mesa libGLw version 8.0.0-18.  Thanks.

**Comment by afni-rickr** [comment]
The extern seems to be in the main mesa/glw git repo as of July 17, 2018.
