### ISSUE TITLE
AFNI Make for arm64 

### ISSUE THREAD

**Issue by roohy466** [afni/afni#535]
Hi I am trying to compile AFNI for ubuntu arm64 and I was successful with default setup. however I need to use more updated python packages that are available in ubuntu 20.04 which the default python is 3.8. I am updating the current python to 3.10 , but CMakeList can not find it and always finds the 3.8! where I have to tell Cmake to use python 3.10?

**Comment by afni-rickr** [comment]
Hello @roohy466,

To be sure, you are using cmake to build, and it is not quite finishing because it is looking for an old python version?  Do you have multiple versions of python on your system then?

Note that we are much more comfortable running a pure 'make' build, and could more easily give instructions on that: [install_instructs/steps_linux_ubuntu20.html](https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu20.html).  Does that help?

**Comment by afni-rickr** [comment]
To be sure, was that a cmake build or a pure make build?
So you were able to compile R_io.so, but then 3dMVM gave this message?  It would be nice if that error check were formulated better, but it seems more likely that R_io.so does not know where to find libmri.so (than libR.so).  But either way points to the build process, so we should go back to that.  Can you show how R_Io.so is built?

**Comment by roohy466** [comment]
the os was Ubuntu 22.04  arm64,   make failed at some point, but cmake finished the process with many warnings. I built the R_io.so this way, as it looked for many libraries , I created a R_io folder copied R_io.c and all *.h files there as well as SUMA folder contains other h files. Then I run this command:

    R CMD SHLIB -o R_io.so R_io.c ;

**Comment by afni-rickr** [comment]
Those are interesting timing details.  It sounds like you are running all of this on a mac, and if the mac needs to translate from x86_64 to amd64, it will indeed slow it down.  We thought it costed closer to 20% time, but it is probably the case that the more CPU intensive something is, the bigger the difference would tend to be.

There is a Makevars file that is created to assist with building R_io.so.  But for kicks, would you just try running a normal make, and see how it goes?
```
build_afni.py -build_root ~/afni_build -package linux_ubuntu_22_64
```
Thanks.

**Comment by roohy466** [comment]
after correcting for many libraries, I got this problem which I dont now how to solve.

      SUMA_Makefile:33: *** Recursive variable 'CC' references itself (eventually).  Stop.

**Comment by roohy466** [comment]
I got error here:

    ++ building (please be patient)...
    ** error: failed run_cmd: make AFNI_WHOMADEIT=build itall >& log_make.txt
    -- status: building FAILURE
       see 'make' log file /home/ubuntu/data/afni_build/build_src/log_make.txt
    ** error: tail from log_make.txt:
       --------------------------------------------------
       ./configure --includedir /usr/include/netpbm ; \
       make clean ;                                \
       make ;                                      \
       /usr/bin/ranlib src/.libs/libgts.a ;	                      \
       cp -p src/.libs/libgts.a .. ; )
       SUMA_Makefile:33: *** Recursive variable 'CC' references itself (eventually).  Stop.
       make[1]: Leaving directory '/home/ubuntu/data/afni_build/build_src/SUMA'
       /bin/cp: cannot stat 'SUMA/libgts.a': No such file or directory
       /bin/cp: cannot stat 'SUMA/libgts.a': No such file or directory
       make: *** [Makefile.INCLUDE:3848: libgts.a] Error 1
       --------------------------------------------------
    
    
    -- shell/system command history is in:
          /home/ubuntu/data/afni_build/hist_commands.txt
    
    ++ screen text history is in:
          /home/ubuntu/data/afni_build/hist_messages.txt

**Comment by afni-rickr** [comment]
Sorry, I have not had time to look into this much yet, but that is a part of the Makefile that should not be getting invoked.  Make sure you do not have CC set when running the make.  Please clear any CC variable(s) (in the command or in your environment) and see if that persists.  Thanks.

**Comment by roohy466** [comment]
now I get another error!

    ++ building (please be patient)...
    -- attempting cmd: make AFNI_WHOMADEIT=build itall >& log_make.txt 
    ** error: failed run_cmd: make AFNI_WHOMADEIT=build itall >& log_make.txt
    -- status: building FAILURE
       see 'make' log file /home/ubuntu/data/afni_buid/build_src/log_make.txt
    ** error: tail from log_make.txt:
       --------------------------------------------------
       /usr/bin/ld: SUMA_dot.o:(.bss+0x1410): multiple definition of `glwDrawingAreaWidgetClass'; SUMA_trackball.o:(.bss+0x8): first defined here
       /usr/bin/ld: SUMA_plot.o:(.bss+0x120): multiple definition of `glwDrawingAreaWidgetClass'; SUMA_trackball.o:(.bss+0x8): first defined here
       /usr/bin/ld: SUMA_volume_render.o:(.bss+0x350): multiple definition of `glwDrawingAreaWidgetClass'; SUMA_trackball.o:(.bss+0x8): first defined here
       /usr/bin/ld: SUMA_driver.o:(.bss+0x8): multiple definition of `glwDrawingAreaWidgetClass'; SUMA_trackball.o:(.bss+0x8): first defined here
       collect2: error: ld returned 1 exit status
       make[1]: *** [SUMA_Makefile_NoDev:162: libSUMA.so] Error 1
       make[1]: Leaving directory '/home/ubuntu/data/afni_buid/build_src/SUMA'
       /bin/cp: cannot stat 'SUMA/libSUMA.so': No such file or directory
       /bin/cp: cannot stat 'SUMA/libSUMA.so': No such file or directory
       make: *** [Makefile.INCLUDE:3829: libSUMA.so] Error 1

**Comment by afni-rickr** [comment]
Oh, that's good.  I think the OS notes for that system might not be consistent with the Makefile (I don't use those systems to verify).  There is a mistake in the official OpenGL header GL/GLwDrawA.h that leads to this.  So either fix that or use a different Makefile.  To fix it (which I prefer), use the commands described in OS_notes.linux_ubuntu_16_64 (they could be shorter, but are done more safely):
```
sudo mv /usr/include/GL/GLwDrawA.h /usr/include/GL/GLwDrawA.h.orig
sudo sed 's/^GLAPI WidgetClass/extern GLAPI WidgetClass/' \
         /usr/include/GL/GLwDrawA.h.orig > ~/tmp_GLwDrawA.h
sudo mv ~/tmp_GLwDrawA.h /usr/include/GL/GLwDrawA.h
```
And then run the build again.  That would be a one-time fix.
Alternatively, you could build with the linux_ubuntu_16_64_glw_local_shared package/Makefile.
```
build_afni.py -build_root ~/afni_build -package linux_ubuntu_16_64_glw_local_shared
```
I would expect either to work.  If fixing the header file works for you, I will add that to the OS_notes file for Ubuntu 22.
Thanks.

**Comment by roohy466** [comment]
Wonderful, seems the problem was solved and seems the build was finished. Got New error!

    ++ building (please be patient)...
    -- status: building SUCCESS
       see 'make' log file /home/ubuntu/data/afni_buid/build_src/log_make.txt
    -- make build AFNI: AFNI_23.3.13, linux_universal, Dec 09 2023
    ++ testing the build results ...
    ** error: failed run_cmd: tcsh scripts_install/test_afni_prog_help.tcsh -bin_dir linux_ubuntu_22_64 >& log_test.txt
    -- status: build testing FAILURE
       see 'testing' log file /home/ubuntu/data/afni_buid/build_src/log_test.txt
    
    -- shell/system command history is in:
          /home/ubuntu/data/afni_buid/hist_commands.txt
    
    ++ screen text history is in:
          /home/ubuntu/data/afni_buid/hist_messages.txt
    
    
    ============================== overview ==============================
    
    ------------------------------
    to rerun make build:
       cd /home/ubuntu/data/afni_buid/build_src
       make itall
    ------------------------------
    to rerun test of make build:
       cd /home/ubuntu/data/afni_buid/build_src
       tcsh scripts_install/test_afni_prog_help.tcsh -bin_dir linux_ubuntu_22_64

**Comment by afni-rickr** [comment]
Oh dear.  The results should be put into your abin (and backed up) by build_afni.py (with the current package getting backed up).
We obviously do not use that Makefile, since it is using linux_universal for the system name and output directory.  But build_afni.py expects the system name and file name to match.  This would be easier if I could actually test this myself.  Sorry.

Anyway, I made a new Makefile.iinux_univeral (identical to current) and modified Makefile.linux_ubuntu_22_64 to build with that actual system name.  So now you should be able to use either.  :)  Try running your same command, but add `-git_tag NONE` so that rather than getting the previous tagged release, it gets the most current master version:
```
build_afni.py -build_root ~/afni_build -package linux_ubuntu_22_64 -git_tag NONE
```
It isn't necessary to run a full new build, but it would be nice to see that it works, and know that you would not need to worry about anything special going forward.
Thanks.

**Comment by roohy466** [comment]
I think it worked!!!  right?

    #17 [13/14] RUN build_afni.py -build_root ~/afni_build -package linux_ubuntu_22_64 -git_tag NONE
    #17 515.5 
    #17 515.5 -- current AFNI: AFNI_23.3.13, linux_openmp_64, Dec 08 2023
    #17 515.5 -- preparing build_root dir, /root/afni_build
    #17 515.5 -- creating build_root dir, /root/afni_build
    #17 515.5 -- running 'git clone' on afni repo ...
    #17 515.5    (please be patient)
    #17 515.5 -- not checking out any git tag
    #17 515.5 -- using repo branch master, tag AFNI_23.3.13-2-g88c61486b
    #17 515.5 -- downloading AFNI atlas package, afni_atlases_dist.tgz
    #17 515.5 -- unpacking atlas package, afni_atlases_dist
    #17 515.5 -- downloading NiiVue, niivue_afni.umd.js
    #17 515.5 
    #17 515.5 -- preparing to run 'make' build of package linux_ubuntu_22_64
    #17 515.5 -- copying README files
    #17 515.5 -- copying other_builds/Makefile.linux_ubuntu_22_64 to Makefile
    #17 515.5 -- building make target 'itall'
    #17 515.5 
    #17 515.5 -- consider monitoring the build in a separate window with:
    #17 515.5        cd /
    #17 515.5        tail -f /root/afni_build/build_src/log_make.txt
    #17 515.5        # use ctrl-c to terminate 'tail' command (not the build)
    #17 515.5 ++ building (please be patient)...
    #17 515.5 -- status: building SUCCESS
    #17 515.5    see 'make' log file /root/afni_build/build_src/log_make.txt
    #17 515.5 -- make build AFNI: AFNI_23.3.13, linux_ubuntu_22_64, Dec 09 2023
    #17 515.5 ++ testing the build results ...
    #17 515.5 -- status: build testing SUCCESS
    #17 515.5    see 'testing' log file /root/afni_build/build_src/log_test.txt
    #17 515.5 
    #17 515.5 -- will install 'make' build results and atlases
    #17 515.5 
    #17 515.5        PLEASE WAIT FOR THE INSTALL TO COMPLETE...
    #17 515.5 
    #17 515.5 ++ backing up /opt/afni-latest to backup.abin.2023_12_09_19_53_41
    #17 515.5    (backup via rsync)
    #17 515.5 -- cleaning old abin
    #17 515.5 ++ installing atlases under /opt/afni-latest
    #17 515.5 ++ installing build results under /opt/afni-latest
    #17 515.5 ++ installing NiiVue under /opt/afni-latest
    #17 515.5 
    #17 515.5 -- shell/system command history is in:
    #17 515.5       /root/afni_build/hist_commands.txt
    #17 515.5 
    #17 515.5 ++ screen text history is in:
    #17 515.5       /root/afni_build/hist_messages.txt
    #17 515.5 
    #17 515.5 
    #17 515.5 ============================== overview ==============================
    #17 515.5 
    #17 515.5 ------------------------------
    #17 515.5 to rerun make build:
    #17 515.5    cd /root/afni_build/build_src
    #17 515.5    make itall
    #17 515.5 ------------------------------
    #17 515.5 to rerun test of make build:
    #17 515.5    cd /root/afni_build/build_src
    #17 515.5    tcsh scripts_install/test_afni_prog_help.tcsh -bin_dir linux_ubuntu_22_64
    #17 515.5 ------------------------------
    #17 515.5 to revert from backup, run:
    #17 515.5    rsync -av backup.abin.2023_12_09_19_53_41/ /opt/afni-latest/
    #17 515.5 ------------------------------
    #17 515.5 atlases installed to   /opt/afni-latest
    #17 515.5         installed from /root/afni_build/afni_atlases_dist
    #17 515.5 ------------------------------
    #17 515.5 binaries installed to   /opt/afni-latest
    #17 515.5          installed from /root/afni_build/build_src/linux_ubuntu_22_64
    #17 515.5 ------------------------------
    #17 515.5 NiiVue installed to /opt/afni-latest
    #17 515.5 ------------------------------
    #17 515.5 have 1 backup abin directories, backup.abin.*
    #17 515.5 
    #17 DONE 516.7s

**Comment by afni-rickr** [comment]
That looks great, thanks for the update!
