### ISSUE TITLE
apqc html reports show focus ring around niivue canvas

### ISSUE THREAD

**Issue by hanayik** [afni/afni#587]
The reports that are displayed with `open_apqc.py` show a focus ring around the Niivue canvas when the canvas is active and the user clicks inside the canvas. 

I think it is more visually appealing to omit the focus ring using some css styling. 

## proposed style addition

add this to `<QC_DIR>/extra_info/styles.css`
```
canvas {
    /* no outlite on focus */
    outline: none;
}
```

## proposed result
<img width="1331" alt="Screenshot 2024-03-14 at 15 53 19" src="https://github.com/afni/afni/assets/5217720/f030eb4b-d03b-4420-9791-1c6485a228bc">

## current behaviour
<img width="1380" alt="Screenshot 2024-03-14 at 15 53 10" src="https://github.com/afni/afni/assets/5217720/9eeaa075-bd6e-42d7-a0c3-0f564966fc9e">

**Comment by mrneont** [comment]
Sounds good to me, @hanayik. Thanks for pointing that out + and providing a fix.  This has been merged in now.
