### ISSUE TITLE
Korean sauna anyone this Sunday to get ready for apocalypse day??

### ISSUE THREAD

**Issue by yarikoptic** [afni/afni#605]
I am flying to IAD around 5pm Sunday and there is a great new Korean sauna nearby. Anyone interested to join?

**Comment by afni-gangc** [comment]
Yarik, it would be wonderful to meet you. However, Paul and I have an early morning flight out of IAD on Sunday.

**Comment by mrneont** [comment]
Indeed, sorry that we will be airships, passing in the daytime.  Have good travels.

**Comment by yarikoptic** [comment]
No problem, safe travels! There will be next times!
