### ISSUE TITLE
BUG: 3dcopy does not retain scl_slope when converting data type

### ISSUE THREAD

**Issue by liningpan** [afni/afni#612]
It appears that when `3dcopy` needs to copy a nifti file where it needs to perform some conversion (`xform == 1` in `thd_niftiread.c THD_open_nifti`), the `scl_slope` field will not be propagated to the output nifti file through `brick_fac` (`scl_slope != 0.0 && scl_inter == 0.0`).

IIUC, when some sort of conversion is necessary, the `brick_fac` is not populated when reading the nifti header but is set when actually loading data. However, metadata for the output dataset is populated before actually loading nifti data (`brick_fac` not set yet). After `brick_fac` is set, the `EDIT_substitute_brick()` doesn't fix `brick_fac`.

https://github.com/afni/afni/blob/66da3b1f80df7946556248fcd46e0a01cc298728/src/3dcopy.c#L197

This means that `scl_slope` is not set in the output file, and the values in the volume is also not scaled properly.

**Comment by afni-rickr** [comment]
Hello @liningpan,
I cannot actually reproduce a problem here.
The case where xform_data is set in THD_open_nifti() does indeed end up clearing the scl_slope and scl_inter fields, but that is because the data has been converted to a new datum (FLOAT32), and those scalars have actually been applied.  The data values are essentially unchanged (subject to truncation).
Is this what you are seeing?  Or can you provide a more detailed example to duplicate a problem?
Thanks,
- rick

**Comment by liningpan** [comment]
I think you can reproduce this with a nifti image where the data type is uint16, `scl_slope != 0`, and `scl_inter == 0`. If you use 3dcopy to copy this image, the output is float32, the voxel values are directly converted from integer, but the `scl_slope` is now set to 0, which is incorrect.

**Comment by afni-rickr** [comment]
That is basically the case I used, though from merely int16.  The scl_* values are applied, since it is converted to float32, and so the scl values are cleared to zero.  Why is that incorrect?  The values are theoretically unchanged.

**Comment by liningpan** [comment]
Here is a simple u16 nifti file

[test_u16.nii.gz](https://github.com/afni/afni/files/15015714/test_u16.nii.gz)

```sh
# convert with nifti_tool
nifti_tool -copy_image -infiles test_u16.nii -convert2dtype NIFTI_TYPE_FLOAT32 -prefix copy_f32_nifti_tool.nii
# copy with 3dcopy
3dcopy test_u16.nii copy_f32_3dcopy.nii
```

```text
> nifti_tool -disp_ci 1 0 0 0 0 0 0 -infiles test_u16.nii

dataset 'test_u16.nii' @ (1 0 0 0 0 0 0)
2
> nifti_tool -disp_ci 1 0 0 0 0 0 0 -infiles copy_f32_nifti_tool.nii

dataset 'copy_f32_nifti_tool.nii' @ (1 0 0 0 0 0 0)
2.0
# data in the 3dcopy version is not scaled
> nifti_tool -disp_ci 1 0 0 0 0 0 0 -infiles copy_f32_3dcopy.nii

dataset 'copy_f32_3dcopy.nii' @ (1 0 0 0 0 0 0)
2.0
> nifti_tool -diff_hdr -field scl_slope -infiles copy_f32_nifti_tool.nii copy_f32_3dcopy.nii
  name                offset  nvals  values
  ------------------- ------  -----  ------
  scl_slope            112      1    5.0
  scl_slope            112      1    0.0     <-- the scl_slope is also not set
```

**Comment by afni-rickr** [comment]
Oh, thanks.  Indeed, uint16 (or any not-directly-supported type) is the difference.
The problem is in THD_load_nifti, where `scale_data` needs to handle `need_copy`.  I will fix this, thanks!

**Comment by afni-rickr** [comment]
See [https://github.com/afni/afni/pull/613](url).
Do you need compiled binaries, or will you build locally (build_afni.py)?
Thanks again, and for the demo to reproduce this!

**Comment by liningpan** [comment]
Thanks! It would be great if we can get compiled binaries with this fix.

**Comment by afni-rickr** [comment]
Sorry I did not see that last night.  We will do a build today, tanks.

**Comment by afni-rickr** [comment]
This should be available now.  Please let me know if you have any questions or issues, thanks!

**Comment by liningpan** [comment]
Thanks a lot! I will check it out.
