### ISSUE TITLE
Unavailability of Docker images for AFNI 24.x.x

### ISSUE THREAD

**Issue by synchon** [afni/afni#623]
Docker Hub search (https://hub.docker.com/r/afni/afni_make_build/tags) only shows me AFNI 23.x.x as the latest while the latest releases are AFNI 24.x.x . It would be great if the CI is fixed so that the automated Docker releases are back again and I can continue using latest AFNI versions via containers.

**Comment by mrneont** [comment]
Indeed.  We do feel the need for this as well, and it has been on our "to do" list for a long time.  We are hoping to get to it soon.  We might try to avoid requiring CircleCI for it, as CircleCI keeps requiring constant alterations.

**Comment by yarikoptic** [comment]
given the workflow state
![image](https://github.com/afni/afni/assets/39889/f4a7b626-fc92-4e79-a709-128022a19e32)
I guess we just need to fix up testing 
- #651 
and that would unblock deployment (upload) of docker images

**Comment by yarikoptic** [comment]
- https://github.com/afni/afni/pull/656

is done, I guess we just need to wait for a new release to see if we get it to docker hub. @afni-rickr @mrneont is release coming any time soon?

**Comment by afni-rickr** [comment]
Yes, we will run a build today, possibly very soon.  Thanks!

**Comment by synchon** [comment]
Thank you @mrneont @yarikoptic @afni-rickr ! It's available now and works for me, closing the issue. :D
