### ISSUE TITLE
Get AFNI data

### ISSUE THREAD

**Issue by TheChymera** [afni/afni#636]
I am using the CMake AFNI build system but can't seem to get `MNI152_2009_template_SSW.nii.gz` installed, which is needed for `@afni_refacer_run`.

It appears to not be part of the release tarball from the github tags of this repository — which in and of itself is good, because it's separating data from code.

Do you know where I could get this and other required data files from?

@leej3

**Comment by TheChymera** [comment]
@yarikoptic found this → https://afni.nimh.nih.gov/pub/dist/atlases/afni_atlases_dist/

Is this the correct place to get the data files from?
If sou, should this be bundled with the AFNI build or can I install it separately and executables will dynamically look for them? if so, where?

**Comment by afni-rickr** [comment]
Yes, that is correct (and there is a corresponding .tgz there).  build_afni.py will download and include that package, but it is not part of the make process.
We generally just include the contents in the main abin directory, but it is common to put them elsewhere, and have the users set AFNI_ATLAS_PATH (in their env or their .afnirc).  Maybe @afni-dglen has additional comments.

**Comment by TheChymera** [comment]
@afni-rickr thank you. Is there any tarball of *all* the atlases, so that I don't have to download them individually?

**Comment by TheChymera** [comment]
also found a bundled version one directory level up :)

**Comment by TheChymera** [comment]
In as far as Gentoo packaging goes it should all be implemented as of https://github.com/gentoo/sci/commit/0075b0aa4f9993e0bc54e9d627329332555d16e0
