### ISSUE TITLE
3dSkullStrip linking to X server libraries?

### ISSUE THREAD

**Issue by oesteban** [afni/afni#66]
We have noticed that, except for AFNI 16.0.00 through 16.2.07, some X server libraries are linked (libGLU I think) and `3dSkullStrip` will not run if a viable `$DISPLAY` is not available. The typical symptoms were reported [here](https://afni.nimh.nih.gov/afni/community/board/read.php?1,149142) before.

This problem is particularly hard on headless setups, where an X server is generally not running. One could try to use `Xvfb` on a random display port, but this solution is not very robust. And once in a while you would get errors like:

```
3dSkullStrip -input /usr/local/src/mriqc/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..data..sub-11..ses-day2..anat..sub-11_ses$
freeglut (3dSkullStrip): failed to open display ':1286930384'
```
with return code 1.

We are aware that there is a wrapper to `Xvfb` in AFNI called `@chauffeur_afni` that addresses this very issue. But the question is: is it really necessary linking these libraries for `3dSkullStrip` to work? If not, it would be very much appreciated to clean up those links for a robuster performance on head-less settings.

**Comment by leej3** [comment]
Yes, this is the case. The newer build  attempts to remove X (or more specifically memory allocation functionality from Xt) from as many of the programs as possible. It is ongoing work. 

Programs in src/SUMA additionally inherit some OpenGL dependencies. 3dSkullStrip being such a lucky entity. That may be harder to disentangle. Closing this as there is no easy fix. If solved it will be part of broader improvements in restricting linking during the build
