### ISSUE TITLE
macOS precompiled binary (macos_10.12_local) issue: driving afni to save images (esp. in @chauffeur_afni)

### ISSUE THREAD

**Issue by mrneont** [afni/afni#668]
The following crash seems to consistently occur when using precompiled macOS binaries macos_10.12_local (observed now on version numbers AFNI_24.1.09, AFNI_24.1.10 and AFNI_24.1.11) when using `@chauffeur_afni` to save images, such as afni_proc.py's QC HTML:
```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++ If you are using XQuartz 2.7.10 (or later), and AFNI crashes when
 + opening windows, or you cannot type text into AFNI popup windows,
 + you might need to set an environment variable to solve this problem:
 +   setenv DYLD_LIBRARY_PATH /opt/X11/lib/flat_namespace    # tcsh
 +   export DYLD_LIBRARY_PATH=/opt/X11/lib/flat_namespace    # bash
 + This command is best put in your startup ~/.cshrc file, so that
 + it will be invoked for every (t)csh shell you open (mutatis mutandis
 + for the bash shell, of course).
 +
 + If things are OK and you want to avoid having this warning message
 + pollute your terminal, use this:
 +   setenv AFNI_SKIP_DYLD_WARNING YES                       # tcsh
 +   export AFNI_SKIP_DYLD_WARNING=YES                       # bash

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Warning: Widget must be a VendorShell.

Fatal Signal 11 (SIGSEGV) received
Last STATUS: creating top_form
     AFNI_make_widgets
    new_AFNI_controller
   MAIN_workprocess
  AFNI:main
 Bottom of Debug Stack
** AFNI version = AFNI_24.1.09  Compile date = May  9 2024
** [[Precompiled binary macos_10.12_local: May  9 2024]]
** Program Death **
** If you report this crash to the AFNI message board,
** please copy the error messages EXACTLY, and give
** the command line you used to run the program, and
** any other information needed to repeat the problem.
** You may later be asked to upload data to help debug.
** Crash log is appended to file /Users/minsunpark/.afni.crashlog
```

This occurs even when the env var `DYLD_LIBRARY_PATH` really does appear to be correctly set in the `~/.*rc` files. 

**The current solution for users** is to compile AFNI locally on their own machines, following the instructions [here for Intel chip](https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_macOS_12_Intel.html)  and [here for ARM/Silicon/M1/M2/M3](https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_macOS_12_Silicon.html).  

We will look more into this crash, though, to resolve it.

**Comment by mrneont** [comment]
Indeed, this happens even if the GUI has been opened. (The issue that is cured just by opening the GUI once or resetting temp file permissions is the one described [here](https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/programs/alpha/%40chauffeur_afni_sphx.html#troubleshooting), I believe.)

This crash occurs on my local macOS Intel laptop.  I haven't tried it on the build system.

**Comment by afni-rickr** [comment]
Oh, this is due to the quick "-f" change made for biowulf.  Adding that means the DYLD vars are not set and the afni GUI crashes.  So on macs using the 10.12 binaries, we cannot use -f in scripts starting the GUI.  On the plus side, we are using whereami_afni, so that change is no longer needed.

**Comment by mrneont** [comment]
OK, @afni-rickr has resolved this issue with this code update (https://github.com/afni/afni/commit/0d76bfc3406bacd1cdf28afd57d836c86e3938ff), as described in this comment update (https://github.com/afni/afni/commit/50fd721749d77f82f94cb712ff87f50944369371). Grazie!

This will be part of our next-and-hopefully-soon build.
