### ISSUE TITLE
Two more instances of using 'count' instead of 'count_afni', one causing sswarper2 to fail

### ISSUE THREAD

**Issue by berndf** [afni/afni#671]
scripts_install/ap_run_simple_rest_me.tcsh
scripts_install/sswarper2

Both scripts use `count ...` which gives wrong results, and in case of sswarper2 leads to the script failing with
"alhi_ct: Index not in valid range"

(I have llvm installed, which comes with a 'count' binary...')

Thanks!
- Bernd

**Comment by mrneont** [comment]
Hi, Bernd-

Ah, sorry for the breakage, and thanks very much for pointing those out!  This commit+push now fixes that (https://github.com/afni/afni/commit/d3e24f72a10b3251ac58b048c5cce93370941472), and we will do a build soon, then.

Cheer,
pt

**Comment by mrneont** [comment]
... and this build (https://github.com/afni/afni/commit/8b432aa575a3305b205312a2a4d45f42994233c1), which just started, contains the updated code.  It should be complete in a couple hours, so that should resolve this. 

Thanks again for bringing it up.

--pt
