### ISSUE TITLE
Dead links in AFNI program documentation

### ISSUE THREAD

**Issue by handwerkerd** [afni/afni#684]
I was looking at https://afni.nimh.nih.gov/pub/dist/doc/program_help/@chauffeur_afni.html and noticed links for other programs, like 3dAutobox and 3dAutomask. The included links are from an older website structure ( https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/programs/3dAutobox_sphx.html & https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/programs/3dAutomask_sphx.html ) rather than https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dAutobox.html and https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dAutomask.html.

I suspect this is an issue with other program docs as well.

**Comment by mrneont** [comment]
@handwerkerd : thanks, I will search around and fix those.

On a sidenote, looking at the Sphinx-ified forms of helps has some nicer features, like tables of contents at hte top:
https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/programs/alpha/%40chauffeur_afni_sphx.html#ahelp-chauffeur-afni

I know google searches still go to the 'plain text' forms.  I'm not sure how to adjust that.

--pt
