### ISSUE TITLE
unexpected exit using 3dWarp -verb -card2oblique

### ISSUE THREAD

**Issue by benoitberanger** [afni/afni#76]
Hello everyone,

With this version `Dec 22 2017 {AFNI_17.3.09:linux_openmp_64}`, I had no problem (described bellow).
I just updated the binaries with `Jun  3 2018 {AFNI_18.1.24:linux_openmp_64}` and this problem appeared with this command : 

> 3dWarp -verb -card2oblique ./run001_e001.nii[0] -overwrite  -newgrid 1.000000 -prefix ./anat_ob.nii.gz /mnt/data/img/Pilote001/meica/anat_ns.nii.gz | \grep  -A 4 '# mat44 Obliquity Transformation ::'  > run001_e001_obla2e_mat.1D

With the **old** version, no problem.

With the **new** version, the script (generated by meica.py) exits, and the file `run001_e001_obla2e_mat.1D` is empty.

Cheers,
Benoît

**Comment by afni-rickr** [comment]
Yes, this just went into the most recent build.  That transformation text was moved from stdout to stderr, so the grep command stopped capturing it.  We are already fixing it, and will run a new build soon.  Thanks for looking into it though!
