### ISSUE TITLE
ENH: allow plugout_drive to access FIM graph menu

### ISSUE THREAD

**Issue by ischwabacher** [afni/afni#9]
I'd like to be able to add additional timeseries to the graph window via plugout_drive in order to improve on the `@epi_review.$subj` script.  Currently, when I'm reviewing a subject's data, I have to carefully cross reference any anomalies I observe in the data with the list of time points that have already been censored.  It would be much quicker if I could simply look at the graph to determine whether action is required on my part.

Preliminary prodding suggests that the internal plumbing [already exists](https://github.com/afni/afni/blob/8fe6f4c4ed603a04298b9ca737d1160ae4e29398/src/afni_graph.c#L5039) and only needs to be connected up to the external driver plumbing, but I haven't looked at it in depth yet.  If it turns out to be easy, I might put in a PR.

**Comment by afni-rwcox** [comment]
(1) Do you mean to have multiple reference time series?
(2) Do you still care?
