### ISSUE TITLE
warning: rewriting history in the AFNI repo

### ISSUE THREAD

**Issue by afni-rickr** [afni/afni#91]
@zsaad @nno @ccraddock @kaczmarj @Shotgunosine @pintohutch @yarikoptic @jlisinski @CesarCaballeroGaudes @imnotamember @pmolfese @hjmjohnson @roopchansinghv @dillonplunkett @DavidEWarrenPhD @rdvincent Hi all, this is a quick warning to anyone working with the AFNI/afni repo. 
@leej3 is about to reduce this repo size, which will rewrite the commit history, basically breaking any currently existing branch (except for those who particularly like to suffer).
Once this change is made, if you want to make edits, start with a fresh copy (fork/clone/pull/whatever) of the repo, before your changes are introduced.
If there is any reason this would be problematic for you, please let us know by Thursday.  Otherwise, the destruction will commence on Friday.  Thanks!

**Comment by yarikoptic** [comment]
did it happen and time to close?

**Comment by leej3** [comment]
Yep, thanks
