### ISSUE TITLE
nibabel under meica.libs need update

### ISSUE THREAD

**Issue by lcnature** [afni/afni#96]
Hello,
There is some recent update in numpy which causes nibabel to fail to load data (see this issue: https://github.com/nipy/nibabel/issues/697). I think nibabel has fixed it. The nibabel version in meica.libs/ seems to include an older version of nibabel which tedana.py will import by default. I have confirmed that by removing the nibabel folder in meica.libs/ folder while having an updated nibabel installed can fix this problem when using the tedana wrapper in AFNI. I suggest updating the nibabel folder to the newest one in meica.libs/
Thanks!

**Comment by emdupre** [comment]
Thanks to @jbteves for the ping on this ! Unfortunately I can't comment on updating the nibabel folder, but I did just want to point to this as fodder for a broader discussion on linking AFNI and [tedana](https://github.com/me-ica/tedana).

We had discussed this previously in https://github.com/ME-ICA/tedana/issues/26 and with @afni-rickr in person. Obviously this would be much more involved than simply updating the shipped version of nibabel, but I wanted to just make the connection explicit :)

**Comment by lcnature** [comment]
@emdupre Thanks a lot for replying about this issue! I have read the thread you mentioned. But it seems that the nibabel issue here is orthogonal to the other discussions you had? I think nibabel is used by tedana to load images. If it fails to load image, then at least the tedana wrapper in AFNI does not work for me. I am fine of removing the shipped version and relying on a separate nibabel in my conda environment, or maybe trying to use an older version of numpy. But I raised this issue because I think other users of the wrapper who happen to have installed the newest numpy would have the same problem.

**Comment by afni-rickr** [comment]
Hi @emdupre, @lcnature, I have still failed to attack tedana in earnest...  But for this issue, it would be (hacky but) easy to try to import nibabel globally before taking the one shipped with our version of tedana.py, using an installed package preferentially over this older copy.  See [ted.nib.hack](https://github.com/afni/afni/compare/ted.nib.hack?expand=1) .  That gets ugly, but it allows people to do what they are already doing.  Seem okay for now?

**Comment by lcnature** [comment]
@afni-rickr Thanks for the hack! I think that would work!

**Comment by mrneont** [comment]
This seems closable, based on the last messages.

Please let us know in the future if this should be revisited.

**Comment by afni-rickr** [comment]
AFNI's tedana.py tries to import a system nibabel before falling back to the local one.

**Comment by leej3** [comment]
Is that desired behavior? If one instead wants to  always find the local
one you could do something like:

```
from pathlib import Path
import sys
execution_dir = Path(__file__).parent
sys.path.append(str(execution_dir))
```
